/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the FraisPreviewResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FraisPreviewResponseV2{}

// FraisPreviewResponseV2 Calcul de frais (preavis). Le montant retourne est celui qui sera reellement debite pour la meme demande.
type FraisPreviewResponseV2 struct {
	// Montant de la transaction demande.
	Montant *float64 `json:"montant,omitempty"`
	// Frais NITA applicables.
	Frais *float64 `json:"frais,omitempty"`
	// Timbre fiscal (0 si non applicable).
	Timbre *float64 `json:"timbre,omitempty"`
	// Reduction appliquee (0 si aucune).
	MontantReduction *float64 `json:"montantReduction,omitempty"`
	// Total debite du compte partenaire.
	MontantDebite *float64 `json:"montantDebite,omitempty"`
	// Montant net recu par le beneficiaire.
	MontantRecu *float64 `json:"montantRecu,omitempty"`
	// true = frais deduits du montant, false = frais en sus.
	FraisInclus *bool `json:"fraisInclus,omitempty"`
	// Devise des montants (XOF).
	Devise *string `json:"devise,omitempty"`
}

// NewFraisPreviewResponseV2 instantiates a new FraisPreviewResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFraisPreviewResponseV2() *FraisPreviewResponseV2 {
	this := FraisPreviewResponseV2{}
	return &this
}

// NewFraisPreviewResponseV2WithDefaults instantiates a new FraisPreviewResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFraisPreviewResponseV2WithDefaults() *FraisPreviewResponseV2 {
	this := FraisPreviewResponseV2{}
	return &this
}

// GetMontant returns the Montant field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetMontant() float64 {
	if o == nil || IsNil(o.Montant) {
		var ret float64
		return ret
	}
	return *o.Montant
}

// GetMontantOk returns a tuple with the Montant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetMontantOk() (*float64, bool) {
	if o == nil || IsNil(o.Montant) {
		return nil, false
	}
	return o.Montant, true
}

// HasMontant returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasMontant() bool {
	if o != nil && !IsNil(o.Montant) {
		return true
	}

	return false
}

// SetMontant gets a reference to the given float64 and assigns it to the Montant field.
func (o *FraisPreviewResponseV2) SetMontant(v float64) {
	o.Montant = &v
}

// GetFrais returns the Frais field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetFrais() float64 {
	if o == nil || IsNil(o.Frais) {
		var ret float64
		return ret
	}
	return *o.Frais
}

// GetFraisOk returns a tuple with the Frais field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetFraisOk() (*float64, bool) {
	if o == nil || IsNil(o.Frais) {
		return nil, false
	}
	return o.Frais, true
}

// HasFrais returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasFrais() bool {
	if o != nil && !IsNil(o.Frais) {
		return true
	}

	return false
}

// SetFrais gets a reference to the given float64 and assigns it to the Frais field.
func (o *FraisPreviewResponseV2) SetFrais(v float64) {
	o.Frais = &v
}

// GetTimbre returns the Timbre field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetTimbre() float64 {
	if o == nil || IsNil(o.Timbre) {
		var ret float64
		return ret
	}
	return *o.Timbre
}

// GetTimbreOk returns a tuple with the Timbre field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetTimbreOk() (*float64, bool) {
	if o == nil || IsNil(o.Timbre) {
		return nil, false
	}
	return o.Timbre, true
}

// HasTimbre returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasTimbre() bool {
	if o != nil && !IsNil(o.Timbre) {
		return true
	}

	return false
}

// SetTimbre gets a reference to the given float64 and assigns it to the Timbre field.
func (o *FraisPreviewResponseV2) SetTimbre(v float64) {
	o.Timbre = &v
}

// GetMontantReduction returns the MontantReduction field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetMontantReduction() float64 {
	if o == nil || IsNil(o.MontantReduction) {
		var ret float64
		return ret
	}
	return *o.MontantReduction
}

// GetMontantReductionOk returns a tuple with the MontantReduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetMontantReductionOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantReduction) {
		return nil, false
	}
	return o.MontantReduction, true
}

// HasMontantReduction returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasMontantReduction() bool {
	if o != nil && !IsNil(o.MontantReduction) {
		return true
	}

	return false
}

// SetMontantReduction gets a reference to the given float64 and assigns it to the MontantReduction field.
func (o *FraisPreviewResponseV2) SetMontantReduction(v float64) {
	o.MontantReduction = &v
}

// GetMontantDebite returns the MontantDebite field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetMontantDebite() float64 {
	if o == nil || IsNil(o.MontantDebite) {
		var ret float64
		return ret
	}
	return *o.MontantDebite
}

// GetMontantDebiteOk returns a tuple with the MontantDebite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetMontantDebiteOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantDebite) {
		return nil, false
	}
	return o.MontantDebite, true
}

// HasMontantDebite returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasMontantDebite() bool {
	if o != nil && !IsNil(o.MontantDebite) {
		return true
	}

	return false
}

// SetMontantDebite gets a reference to the given float64 and assigns it to the MontantDebite field.
func (o *FraisPreviewResponseV2) SetMontantDebite(v float64) {
	o.MontantDebite = &v
}

// GetMontantRecu returns the MontantRecu field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetMontantRecu() float64 {
	if o == nil || IsNil(o.MontantRecu) {
		var ret float64
		return ret
	}
	return *o.MontantRecu
}

// GetMontantRecuOk returns a tuple with the MontantRecu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetMontantRecuOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantRecu) {
		return nil, false
	}
	return o.MontantRecu, true
}

// HasMontantRecu returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasMontantRecu() bool {
	if o != nil && !IsNil(o.MontantRecu) {
		return true
	}

	return false
}

// SetMontantRecu gets a reference to the given float64 and assigns it to the MontantRecu field.
func (o *FraisPreviewResponseV2) SetMontantRecu(v float64) {
	o.MontantRecu = &v
}

// GetFraisInclus returns the FraisInclus field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetFraisInclus() bool {
	if o == nil || IsNil(o.FraisInclus) {
		var ret bool
		return ret
	}
	return *o.FraisInclus
}

// GetFraisInclusOk returns a tuple with the FraisInclus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetFraisInclusOk() (*bool, bool) {
	if o == nil || IsNil(o.FraisInclus) {
		return nil, false
	}
	return o.FraisInclus, true
}

// HasFraisInclus returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasFraisInclus() bool {
	if o != nil && !IsNil(o.FraisInclus) {
		return true
	}

	return false
}

// SetFraisInclus gets a reference to the given bool and assigns it to the FraisInclus field.
func (o *FraisPreviewResponseV2) SetFraisInclus(v bool) {
	o.FraisInclus = &v
}

// GetDevise returns the Devise field value if set, zero value otherwise.
func (o *FraisPreviewResponseV2) GetDevise() string {
	if o == nil || IsNil(o.Devise) {
		var ret string
		return ret
	}
	return *o.Devise
}

// GetDeviseOk returns a tuple with the Devise field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FraisPreviewResponseV2) GetDeviseOk() (*string, bool) {
	if o == nil || IsNil(o.Devise) {
		return nil, false
	}
	return o.Devise, true
}

// HasDevise returns a boolean if a field has been set.
func (o *FraisPreviewResponseV2) HasDevise() bool {
	if o != nil && !IsNil(o.Devise) {
		return true
	}

	return false
}

// SetDevise gets a reference to the given string and assigns it to the Devise field.
func (o *FraisPreviewResponseV2) SetDevise(v string) {
	o.Devise = &v
}

func (o FraisPreviewResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FraisPreviewResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Montant) {
		toSerialize["montant"] = o.Montant
	}
	if !IsNil(o.Frais) {
		toSerialize["frais"] = o.Frais
	}
	if !IsNil(o.Timbre) {
		toSerialize["timbre"] = o.Timbre
	}
	if !IsNil(o.MontantReduction) {
		toSerialize["montantReduction"] = o.MontantReduction
	}
	if !IsNil(o.MontantDebite) {
		toSerialize["montantDebite"] = o.MontantDebite
	}
	if !IsNil(o.MontantRecu) {
		toSerialize["montantRecu"] = o.MontantRecu
	}
	if !IsNil(o.FraisInclus) {
		toSerialize["fraisInclus"] = o.FraisInclus
	}
	if !IsNil(o.Devise) {
		toSerialize["devise"] = o.Devise
	}
	return toSerialize, nil
}

type NullableFraisPreviewResponseV2 struct {
	value *FraisPreviewResponseV2
	isSet bool
}

func (v NullableFraisPreviewResponseV2) Get() *FraisPreviewResponseV2 {
	return v.value
}

func (v *NullableFraisPreviewResponseV2) Set(val *FraisPreviewResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableFraisPreviewResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableFraisPreviewResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFraisPreviewResponseV2(val *FraisPreviewResponseV2) *NullableFraisPreviewResponseV2 {
	return &NullableFraisPreviewResponseV2{value: val, isSet: true}
}

func (v NullableFraisPreviewResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFraisPreviewResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


