/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the PartenaireToWalletModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartenaireToWalletModel{}

// PartenaireToWalletModel struct for PartenaireToWalletModel
type PartenaireToWalletModel struct {
	PhoneClient *string `json:"phoneClient,omitempty"`
	MontantTransaction *float64 `json:"montantTransaction,omitempty"`
	LongTransaction *string `json:"longTransaction,omitempty"`
	LatTransaction *string `json:"latTransaction,omitempty"`
	MotifTransaction *string `json:"motifTransaction,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	AdresseIp *string `json:"adresseIp,omitempty"`
	PhoneDeposant *string `json:"phoneDeposant,omitempty"`
	NomDeposant *string `json:"nomDeposant,omitempty"`
	PrenomDeposant *string `json:"prenomDeposant,omitempty"`
	TypePieceDeposant *string `json:"typePieceDeposant,omitempty"`
	NumeroPieceDeposant *string `json:"numeroPieceDeposant,omitempty"`
}

// NewPartenaireToWalletModel instantiates a new PartenaireToWalletModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartenaireToWalletModel() *PartenaireToWalletModel {
	this := PartenaireToWalletModel{}
	return &this
}

// NewPartenaireToWalletModelWithDefaults instantiates a new PartenaireToWalletModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartenaireToWalletModelWithDefaults() *PartenaireToWalletModel {
	this := PartenaireToWalletModel{}
	return &this
}

// GetPhoneClient returns the PhoneClient field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetPhoneClient() string {
	if o == nil || IsNil(o.PhoneClient) {
		var ret string
		return ret
	}
	return *o.PhoneClient
}

// GetPhoneClientOk returns a tuple with the PhoneClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetPhoneClientOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneClient) {
		return nil, false
	}
	return o.PhoneClient, true
}

// HasPhoneClient returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasPhoneClient() bool {
	if o != nil && !IsNil(o.PhoneClient) {
		return true
	}

	return false
}

// SetPhoneClient gets a reference to the given string and assigns it to the PhoneClient field.
func (o *PartenaireToWalletModel) SetPhoneClient(v string) {
	o.PhoneClient = &v
}

// GetMontantTransaction returns the MontantTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetMontantTransaction() float64 {
	if o == nil || IsNil(o.MontantTransaction) {
		var ret float64
		return ret
	}
	return *o.MontantTransaction
}

// GetMontantTransactionOk returns a tuple with the MontantTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetMontantTransactionOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantTransaction) {
		return nil, false
	}
	return o.MontantTransaction, true
}

// HasMontantTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasMontantTransaction() bool {
	if o != nil && !IsNil(o.MontantTransaction) {
		return true
	}

	return false
}

// SetMontantTransaction gets a reference to the given float64 and assigns it to the MontantTransaction field.
func (o *PartenaireToWalletModel) SetMontantTransaction(v float64) {
	o.MontantTransaction = &v
}

// GetLongTransaction returns the LongTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetLongTransaction() string {
	if o == nil || IsNil(o.LongTransaction) {
		var ret string
		return ret
	}
	return *o.LongTransaction
}

// GetLongTransactionOk returns a tuple with the LongTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetLongTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.LongTransaction) {
		return nil, false
	}
	return o.LongTransaction, true
}

// HasLongTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasLongTransaction() bool {
	if o != nil && !IsNil(o.LongTransaction) {
		return true
	}

	return false
}

// SetLongTransaction gets a reference to the given string and assigns it to the LongTransaction field.
func (o *PartenaireToWalletModel) SetLongTransaction(v string) {
	o.LongTransaction = &v
}

// GetLatTransaction returns the LatTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetLatTransaction() string {
	if o == nil || IsNil(o.LatTransaction) {
		var ret string
		return ret
	}
	return *o.LatTransaction
}

// GetLatTransactionOk returns a tuple with the LatTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetLatTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.LatTransaction) {
		return nil, false
	}
	return o.LatTransaction, true
}

// HasLatTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasLatTransaction() bool {
	if o != nil && !IsNil(o.LatTransaction) {
		return true
	}

	return false
}

// SetLatTransaction gets a reference to the given string and assigns it to the LatTransaction field.
func (o *PartenaireToWalletModel) SetLatTransaction(v string) {
	o.LatTransaction = &v
}

// GetMotifTransaction returns the MotifTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetMotifTransaction() string {
	if o == nil || IsNil(o.MotifTransaction) {
		var ret string
		return ret
	}
	return *o.MotifTransaction
}

// GetMotifTransactionOk returns a tuple with the MotifTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetMotifTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.MotifTransaction) {
		return nil, false
	}
	return o.MotifTransaction, true
}

// HasMotifTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasMotifTransaction() bool {
	if o != nil && !IsNil(o.MotifTransaction) {
		return true
	}

	return false
}

// SetMotifTransaction gets a reference to the given string and assigns it to the MotifTransaction field.
func (o *PartenaireToWalletModel) SetMotifTransaction(v string) {
	o.MotifTransaction = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *PartenaireToWalletModel) SetRequestId(v string) {
	o.RequestId = &v
}

// GetAdresseIp returns the AdresseIp field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetAdresseIp() string {
	if o == nil || IsNil(o.AdresseIp) {
		var ret string
		return ret
	}
	return *o.AdresseIp
}

// GetAdresseIpOk returns a tuple with the AdresseIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetAdresseIpOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIp) {
		return nil, false
	}
	return o.AdresseIp, true
}

// HasAdresseIp returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasAdresseIp() bool {
	if o != nil && !IsNil(o.AdresseIp) {
		return true
	}

	return false
}

// SetAdresseIp gets a reference to the given string and assigns it to the AdresseIp field.
func (o *PartenaireToWalletModel) SetAdresseIp(v string) {
	o.AdresseIp = &v
}

// GetPhoneDeposant returns the PhoneDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetPhoneDeposant() string {
	if o == nil || IsNil(o.PhoneDeposant) {
		var ret string
		return ret
	}
	return *o.PhoneDeposant
}

// GetPhoneDeposantOk returns a tuple with the PhoneDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetPhoneDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneDeposant) {
		return nil, false
	}
	return o.PhoneDeposant, true
}

// HasPhoneDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasPhoneDeposant() bool {
	if o != nil && !IsNil(o.PhoneDeposant) {
		return true
	}

	return false
}

// SetPhoneDeposant gets a reference to the given string and assigns it to the PhoneDeposant field.
func (o *PartenaireToWalletModel) SetPhoneDeposant(v string) {
	o.PhoneDeposant = &v
}

// GetNomDeposant returns the NomDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetNomDeposant() string {
	if o == nil || IsNil(o.NomDeposant) {
		var ret string
		return ret
	}
	return *o.NomDeposant
}

// GetNomDeposantOk returns a tuple with the NomDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetNomDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.NomDeposant) {
		return nil, false
	}
	return o.NomDeposant, true
}

// HasNomDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasNomDeposant() bool {
	if o != nil && !IsNil(o.NomDeposant) {
		return true
	}

	return false
}

// SetNomDeposant gets a reference to the given string and assigns it to the NomDeposant field.
func (o *PartenaireToWalletModel) SetNomDeposant(v string) {
	o.NomDeposant = &v
}

// GetPrenomDeposant returns the PrenomDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetPrenomDeposant() string {
	if o == nil || IsNil(o.PrenomDeposant) {
		var ret string
		return ret
	}
	return *o.PrenomDeposant
}

// GetPrenomDeposantOk returns a tuple with the PrenomDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetPrenomDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomDeposant) {
		return nil, false
	}
	return o.PrenomDeposant, true
}

// HasPrenomDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasPrenomDeposant() bool {
	if o != nil && !IsNil(o.PrenomDeposant) {
		return true
	}

	return false
}

// SetPrenomDeposant gets a reference to the given string and assigns it to the PrenomDeposant field.
func (o *PartenaireToWalletModel) SetPrenomDeposant(v string) {
	o.PrenomDeposant = &v
}

// GetTypePieceDeposant returns the TypePieceDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetTypePieceDeposant() string {
	if o == nil || IsNil(o.TypePieceDeposant) {
		var ret string
		return ret
	}
	return *o.TypePieceDeposant
}

// GetTypePieceDeposantOk returns a tuple with the TypePieceDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetTypePieceDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.TypePieceDeposant) {
		return nil, false
	}
	return o.TypePieceDeposant, true
}

// HasTypePieceDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasTypePieceDeposant() bool {
	if o != nil && !IsNil(o.TypePieceDeposant) {
		return true
	}

	return false
}

// SetTypePieceDeposant gets a reference to the given string and assigns it to the TypePieceDeposant field.
func (o *PartenaireToWalletModel) SetTypePieceDeposant(v string) {
	o.TypePieceDeposant = &v
}

// GetNumeroPieceDeposant returns the NumeroPieceDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletModel) GetNumeroPieceDeposant() string {
	if o == nil || IsNil(o.NumeroPieceDeposant) {
		var ret string
		return ret
	}
	return *o.NumeroPieceDeposant
}

// GetNumeroPieceDeposantOk returns a tuple with the NumeroPieceDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletModel) GetNumeroPieceDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.NumeroPieceDeposant) {
		return nil, false
	}
	return o.NumeroPieceDeposant, true
}

// HasNumeroPieceDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletModel) HasNumeroPieceDeposant() bool {
	if o != nil && !IsNil(o.NumeroPieceDeposant) {
		return true
	}

	return false
}

// SetNumeroPieceDeposant gets a reference to the given string and assigns it to the NumeroPieceDeposant field.
func (o *PartenaireToWalletModel) SetNumeroPieceDeposant(v string) {
	o.NumeroPieceDeposant = &v
}

func (o PartenaireToWalletModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartenaireToWalletModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PhoneClient) {
		toSerialize["phoneClient"] = o.PhoneClient
	}
	if !IsNil(o.MontantTransaction) {
		toSerialize["montantTransaction"] = o.MontantTransaction
	}
	if !IsNil(o.LongTransaction) {
		toSerialize["longTransaction"] = o.LongTransaction
	}
	if !IsNil(o.LatTransaction) {
		toSerialize["latTransaction"] = o.LatTransaction
	}
	if !IsNil(o.MotifTransaction) {
		toSerialize["motifTransaction"] = o.MotifTransaction
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.AdresseIp) {
		toSerialize["adresseIp"] = o.AdresseIp
	}
	if !IsNil(o.PhoneDeposant) {
		toSerialize["phoneDeposant"] = o.PhoneDeposant
	}
	if !IsNil(o.NomDeposant) {
		toSerialize["nomDeposant"] = o.NomDeposant
	}
	if !IsNil(o.PrenomDeposant) {
		toSerialize["prenomDeposant"] = o.PrenomDeposant
	}
	if !IsNil(o.TypePieceDeposant) {
		toSerialize["typePieceDeposant"] = o.TypePieceDeposant
	}
	if !IsNil(o.NumeroPieceDeposant) {
		toSerialize["numeroPieceDeposant"] = o.NumeroPieceDeposant
	}
	return toSerialize, nil
}

type NullablePartenaireToWalletModel struct {
	value *PartenaireToWalletModel
	isSet bool
}

func (v NullablePartenaireToWalletModel) Get() *PartenaireToWalletModel {
	return v.value
}

func (v *NullablePartenaireToWalletModel) Set(val *PartenaireToWalletModel) {
	v.value = val
	v.isSet = true
}

func (v NullablePartenaireToWalletModel) IsSet() bool {
	return v.isSet
}

func (v *NullablePartenaireToWalletModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartenaireToWalletModel(val *PartenaireToWalletModel) *NullablePartenaireToWalletModel {
	return &NullablePartenaireToWalletModel{value: val, isSet: true}
}

func (v NullablePartenaireToWalletModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartenaireToWalletModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


