/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the ModelEditEnvoieRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelEditEnvoieRequest{}

// ModelEditEnvoieRequest struct for ModelEditEnvoieRequest
type ModelEditEnvoieRequest struct {
	VilleDestination *string `json:"villeDestination,omitempty"`
	NomDestinateur *string `json:"nomDestinateur,omitempty"`
	PrenomDestinateur *string `json:"prenomDestinateur,omitempty"`
	NomExpediteur *string `json:"nomExpediteur,omitempty"`
	PrenomExpediteur *string `json:"prenomExpediteur,omitempty"`
	PhoneExpediteur *string `json:"phoneExpediteur,omitempty"`
	PhoneDestinateur *string `json:"phoneDestinateur,omitempty"`
	MotifEnvoi *string `json:"motifEnvoi,omitempty"`
	CodeEnvoi *string `json:"codeEnvoi,omitempty"`
	MontantEnvoi *float64 `json:"montantEnvoi,omitempty"`
	FraisEnvoi *float64 `json:"fraisEnvoi,omitempty"`
	Total *float64 `json:"total,omitempty"`
	FraisInclus *bool `json:"fraisInclus,omitempty"`
}

// NewModelEditEnvoieRequest instantiates a new ModelEditEnvoieRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelEditEnvoieRequest() *ModelEditEnvoieRequest {
	this := ModelEditEnvoieRequest{}
	return &this
}

// NewModelEditEnvoieRequestWithDefaults instantiates a new ModelEditEnvoieRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelEditEnvoieRequestWithDefaults() *ModelEditEnvoieRequest {
	this := ModelEditEnvoieRequest{}
	return &this
}

// GetVilleDestination returns the VilleDestination field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetVilleDestination() string {
	if o == nil || IsNil(o.VilleDestination) {
		var ret string
		return ret
	}
	return *o.VilleDestination
}

// GetVilleDestinationOk returns a tuple with the VilleDestination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetVilleDestinationOk() (*string, bool) {
	if o == nil || IsNil(o.VilleDestination) {
		return nil, false
	}
	return o.VilleDestination, true
}

// HasVilleDestination returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasVilleDestination() bool {
	if o != nil && !IsNil(o.VilleDestination) {
		return true
	}

	return false
}

// SetVilleDestination gets a reference to the given string and assigns it to the VilleDestination field.
func (o *ModelEditEnvoieRequest) SetVilleDestination(v string) {
	o.VilleDestination = &v
}

// GetNomDestinateur returns the NomDestinateur field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetNomDestinateur() string {
	if o == nil || IsNil(o.NomDestinateur) {
		var ret string
		return ret
	}
	return *o.NomDestinateur
}

// GetNomDestinateurOk returns a tuple with the NomDestinateur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetNomDestinateurOk() (*string, bool) {
	if o == nil || IsNil(o.NomDestinateur) {
		return nil, false
	}
	return o.NomDestinateur, true
}

// HasNomDestinateur returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasNomDestinateur() bool {
	if o != nil && !IsNil(o.NomDestinateur) {
		return true
	}

	return false
}

// SetNomDestinateur gets a reference to the given string and assigns it to the NomDestinateur field.
func (o *ModelEditEnvoieRequest) SetNomDestinateur(v string) {
	o.NomDestinateur = &v
}

// GetPrenomDestinateur returns the PrenomDestinateur field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetPrenomDestinateur() string {
	if o == nil || IsNil(o.PrenomDestinateur) {
		var ret string
		return ret
	}
	return *o.PrenomDestinateur
}

// GetPrenomDestinateurOk returns a tuple with the PrenomDestinateur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetPrenomDestinateurOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomDestinateur) {
		return nil, false
	}
	return o.PrenomDestinateur, true
}

// HasPrenomDestinateur returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasPrenomDestinateur() bool {
	if o != nil && !IsNil(o.PrenomDestinateur) {
		return true
	}

	return false
}

// SetPrenomDestinateur gets a reference to the given string and assigns it to the PrenomDestinateur field.
func (o *ModelEditEnvoieRequest) SetPrenomDestinateur(v string) {
	o.PrenomDestinateur = &v
}

// GetNomExpediteur returns the NomExpediteur field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetNomExpediteur() string {
	if o == nil || IsNil(o.NomExpediteur) {
		var ret string
		return ret
	}
	return *o.NomExpediteur
}

// GetNomExpediteurOk returns a tuple with the NomExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetNomExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.NomExpediteur) {
		return nil, false
	}
	return o.NomExpediteur, true
}

// HasNomExpediteur returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasNomExpediteur() bool {
	if o != nil && !IsNil(o.NomExpediteur) {
		return true
	}

	return false
}

// SetNomExpediteur gets a reference to the given string and assigns it to the NomExpediteur field.
func (o *ModelEditEnvoieRequest) SetNomExpediteur(v string) {
	o.NomExpediteur = &v
}

// GetPrenomExpediteur returns the PrenomExpediteur field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetPrenomExpediteur() string {
	if o == nil || IsNil(o.PrenomExpediteur) {
		var ret string
		return ret
	}
	return *o.PrenomExpediteur
}

// GetPrenomExpediteurOk returns a tuple with the PrenomExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetPrenomExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomExpediteur) {
		return nil, false
	}
	return o.PrenomExpediteur, true
}

// HasPrenomExpediteur returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasPrenomExpediteur() bool {
	if o != nil && !IsNil(o.PrenomExpediteur) {
		return true
	}

	return false
}

// SetPrenomExpediteur gets a reference to the given string and assigns it to the PrenomExpediteur field.
func (o *ModelEditEnvoieRequest) SetPrenomExpediteur(v string) {
	o.PrenomExpediteur = &v
}

// GetPhoneExpediteur returns the PhoneExpediteur field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetPhoneExpediteur() string {
	if o == nil || IsNil(o.PhoneExpediteur) {
		var ret string
		return ret
	}
	return *o.PhoneExpediteur
}

// GetPhoneExpediteurOk returns a tuple with the PhoneExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetPhoneExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneExpediteur) {
		return nil, false
	}
	return o.PhoneExpediteur, true
}

// HasPhoneExpediteur returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasPhoneExpediteur() bool {
	if o != nil && !IsNil(o.PhoneExpediteur) {
		return true
	}

	return false
}

// SetPhoneExpediteur gets a reference to the given string and assigns it to the PhoneExpediteur field.
func (o *ModelEditEnvoieRequest) SetPhoneExpediteur(v string) {
	o.PhoneExpediteur = &v
}

// GetPhoneDestinateur returns the PhoneDestinateur field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetPhoneDestinateur() string {
	if o == nil || IsNil(o.PhoneDestinateur) {
		var ret string
		return ret
	}
	return *o.PhoneDestinateur
}

// GetPhoneDestinateurOk returns a tuple with the PhoneDestinateur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetPhoneDestinateurOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneDestinateur) {
		return nil, false
	}
	return o.PhoneDestinateur, true
}

// HasPhoneDestinateur returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasPhoneDestinateur() bool {
	if o != nil && !IsNil(o.PhoneDestinateur) {
		return true
	}

	return false
}

// SetPhoneDestinateur gets a reference to the given string and assigns it to the PhoneDestinateur field.
func (o *ModelEditEnvoieRequest) SetPhoneDestinateur(v string) {
	o.PhoneDestinateur = &v
}

// GetMotifEnvoi returns the MotifEnvoi field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetMotifEnvoi() string {
	if o == nil || IsNil(o.MotifEnvoi) {
		var ret string
		return ret
	}
	return *o.MotifEnvoi
}

// GetMotifEnvoiOk returns a tuple with the MotifEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetMotifEnvoiOk() (*string, bool) {
	if o == nil || IsNil(o.MotifEnvoi) {
		return nil, false
	}
	return o.MotifEnvoi, true
}

// HasMotifEnvoi returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasMotifEnvoi() bool {
	if o != nil && !IsNil(o.MotifEnvoi) {
		return true
	}

	return false
}

// SetMotifEnvoi gets a reference to the given string and assigns it to the MotifEnvoi field.
func (o *ModelEditEnvoieRequest) SetMotifEnvoi(v string) {
	o.MotifEnvoi = &v
}

// GetCodeEnvoi returns the CodeEnvoi field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetCodeEnvoi() string {
	if o == nil || IsNil(o.CodeEnvoi) {
		var ret string
		return ret
	}
	return *o.CodeEnvoi
}

// GetCodeEnvoiOk returns a tuple with the CodeEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetCodeEnvoiOk() (*string, bool) {
	if o == nil || IsNil(o.CodeEnvoi) {
		return nil, false
	}
	return o.CodeEnvoi, true
}

// HasCodeEnvoi returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasCodeEnvoi() bool {
	if o != nil && !IsNil(o.CodeEnvoi) {
		return true
	}

	return false
}

// SetCodeEnvoi gets a reference to the given string and assigns it to the CodeEnvoi field.
func (o *ModelEditEnvoieRequest) SetCodeEnvoi(v string) {
	o.CodeEnvoi = &v
}

// GetMontantEnvoi returns the MontantEnvoi field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetMontantEnvoi() float64 {
	if o == nil || IsNil(o.MontantEnvoi) {
		var ret float64
		return ret
	}
	return *o.MontantEnvoi
}

// GetMontantEnvoiOk returns a tuple with the MontantEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetMontantEnvoiOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantEnvoi) {
		return nil, false
	}
	return o.MontantEnvoi, true
}

// HasMontantEnvoi returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasMontantEnvoi() bool {
	if o != nil && !IsNil(o.MontantEnvoi) {
		return true
	}

	return false
}

// SetMontantEnvoi gets a reference to the given float64 and assigns it to the MontantEnvoi field.
func (o *ModelEditEnvoieRequest) SetMontantEnvoi(v float64) {
	o.MontantEnvoi = &v
}

// GetFraisEnvoi returns the FraisEnvoi field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetFraisEnvoi() float64 {
	if o == nil || IsNil(o.FraisEnvoi) {
		var ret float64
		return ret
	}
	return *o.FraisEnvoi
}

// GetFraisEnvoiOk returns a tuple with the FraisEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetFraisEnvoiOk() (*float64, bool) {
	if o == nil || IsNil(o.FraisEnvoi) {
		return nil, false
	}
	return o.FraisEnvoi, true
}

// HasFraisEnvoi returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasFraisEnvoi() bool {
	if o != nil && !IsNil(o.FraisEnvoi) {
		return true
	}

	return false
}

// SetFraisEnvoi gets a reference to the given float64 and assigns it to the FraisEnvoi field.
func (o *ModelEditEnvoieRequest) SetFraisEnvoi(v float64) {
	o.FraisEnvoi = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetTotal() float64 {
	if o == nil || IsNil(o.Total) {
		var ret float64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetTotalOk() (*float64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float64 and assigns it to the Total field.
func (o *ModelEditEnvoieRequest) SetTotal(v float64) {
	o.Total = &v
}

// GetFraisInclus returns the FraisInclus field value if set, zero value otherwise.
func (o *ModelEditEnvoieRequest) GetFraisInclus() bool {
	if o == nil || IsNil(o.FraisInclus) {
		var ret bool
		return ret
	}
	return *o.FraisInclus
}

// GetFraisInclusOk returns a tuple with the FraisInclus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelEditEnvoieRequest) GetFraisInclusOk() (*bool, bool) {
	if o == nil || IsNil(o.FraisInclus) {
		return nil, false
	}
	return o.FraisInclus, true
}

// HasFraisInclus returns a boolean if a field has been set.
func (o *ModelEditEnvoieRequest) HasFraisInclus() bool {
	if o != nil && !IsNil(o.FraisInclus) {
		return true
	}

	return false
}

// SetFraisInclus gets a reference to the given bool and assigns it to the FraisInclus field.
func (o *ModelEditEnvoieRequest) SetFraisInclus(v bool) {
	o.FraisInclus = &v
}

func (o ModelEditEnvoieRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelEditEnvoieRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.VilleDestination) {
		toSerialize["villeDestination"] = o.VilleDestination
	}
	if !IsNil(o.NomDestinateur) {
		toSerialize["nomDestinateur"] = o.NomDestinateur
	}
	if !IsNil(o.PrenomDestinateur) {
		toSerialize["prenomDestinateur"] = o.PrenomDestinateur
	}
	if !IsNil(o.NomExpediteur) {
		toSerialize["nomExpediteur"] = o.NomExpediteur
	}
	if !IsNil(o.PrenomExpediteur) {
		toSerialize["prenomExpediteur"] = o.PrenomExpediteur
	}
	if !IsNil(o.PhoneExpediteur) {
		toSerialize["phoneExpediteur"] = o.PhoneExpediteur
	}
	if !IsNil(o.PhoneDestinateur) {
		toSerialize["phoneDestinateur"] = o.PhoneDestinateur
	}
	if !IsNil(o.MotifEnvoi) {
		toSerialize["motifEnvoi"] = o.MotifEnvoi
	}
	if !IsNil(o.CodeEnvoi) {
		toSerialize["codeEnvoi"] = o.CodeEnvoi
	}
	if !IsNil(o.MontantEnvoi) {
		toSerialize["montantEnvoi"] = o.MontantEnvoi
	}
	if !IsNil(o.FraisEnvoi) {
		toSerialize["fraisEnvoi"] = o.FraisEnvoi
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.FraisInclus) {
		toSerialize["fraisInclus"] = o.FraisInclus
	}
	return toSerialize, nil
}

type NullableModelEditEnvoieRequest struct {
	value *ModelEditEnvoieRequest
	isSet bool
}

func (v NullableModelEditEnvoieRequest) Get() *ModelEditEnvoieRequest {
	return v.value
}

func (v *NullableModelEditEnvoieRequest) Set(val *ModelEditEnvoieRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableModelEditEnvoieRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableModelEditEnvoieRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelEditEnvoieRequest(val *ModelEditEnvoieRequest) *NullableModelEditEnvoieRequest {
	return &NullableModelEditEnvoieRequest{value: val, isSet: true}
}

func (v NullableModelEditEnvoieRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelEditEnvoieRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


