/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AnnulePartenaireToWalletModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AnnulePartenaireToWalletModel{}

// AnnulePartenaireToWalletModel struct for AnnulePartenaireToWalletModel
type AnnulePartenaireToWalletModel struct {
	RequestId string `json:"requestId"`
	CodeRecharge string `json:"codeRecharge"`
	AdresseIp string `json:"adresseIp"`
	MotifAnnulation string `json:"motifAnnulation"`
}

type _AnnulePartenaireToWalletModel AnnulePartenaireToWalletModel

// NewAnnulePartenaireToWalletModel instantiates a new AnnulePartenaireToWalletModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAnnulePartenaireToWalletModel(requestId string, codeRecharge string, adresseIp string, motifAnnulation string) *AnnulePartenaireToWalletModel {
	this := AnnulePartenaireToWalletModel{}
	this.RequestId = requestId
	this.CodeRecharge = codeRecharge
	this.AdresseIp = adresseIp
	this.MotifAnnulation = motifAnnulation
	return &this
}

// NewAnnulePartenaireToWalletModelWithDefaults instantiates a new AnnulePartenaireToWalletModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAnnulePartenaireToWalletModelWithDefaults() *AnnulePartenaireToWalletModel {
	this := AnnulePartenaireToWalletModel{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *AnnulePartenaireToWalletModel) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *AnnulePartenaireToWalletModel) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *AnnulePartenaireToWalletModel) SetRequestId(v string) {
	o.RequestId = v
}

// GetCodeRecharge returns the CodeRecharge field value
func (o *AnnulePartenaireToWalletModel) GetCodeRecharge() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeRecharge
}

// GetCodeRechargeOk returns a tuple with the CodeRecharge field value
// and a boolean to check if the value has been set.
func (o *AnnulePartenaireToWalletModel) GetCodeRechargeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeRecharge, true
}

// SetCodeRecharge sets field value
func (o *AnnulePartenaireToWalletModel) SetCodeRecharge(v string) {
	o.CodeRecharge = v
}

// GetAdresseIp returns the AdresseIp field value
func (o *AnnulePartenaireToWalletModel) GetAdresseIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdresseIp
}

// GetAdresseIpOk returns a tuple with the AdresseIp field value
// and a boolean to check if the value has been set.
func (o *AnnulePartenaireToWalletModel) GetAdresseIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdresseIp, true
}

// SetAdresseIp sets field value
func (o *AnnulePartenaireToWalletModel) SetAdresseIp(v string) {
	o.AdresseIp = v
}

// GetMotifAnnulation returns the MotifAnnulation field value
func (o *AnnulePartenaireToWalletModel) GetMotifAnnulation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MotifAnnulation
}

// GetMotifAnnulationOk returns a tuple with the MotifAnnulation field value
// and a boolean to check if the value has been set.
func (o *AnnulePartenaireToWalletModel) GetMotifAnnulationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MotifAnnulation, true
}

// SetMotifAnnulation sets field value
func (o *AnnulePartenaireToWalletModel) SetMotifAnnulation(v string) {
	o.MotifAnnulation = v
}

func (o AnnulePartenaireToWalletModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AnnulePartenaireToWalletModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["codeRecharge"] = o.CodeRecharge
	toSerialize["adresseIp"] = o.AdresseIp
	toSerialize["motifAnnulation"] = o.MotifAnnulation
	return toSerialize, nil
}

func (o *AnnulePartenaireToWalletModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"codeRecharge",
		"adresseIp",
		"motifAnnulation",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAnnulePartenaireToWalletModel := _AnnulePartenaireToWalletModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAnnulePartenaireToWalletModel)

	if err != nil {
		return err
	}

	*o = AnnulePartenaireToWalletModel(varAnnulePartenaireToWalletModel)

	return err
}

type NullableAnnulePartenaireToWalletModel struct {
	value *AnnulePartenaireToWalletModel
	isSet bool
}

func (v NullableAnnulePartenaireToWalletModel) Get() *AnnulePartenaireToWalletModel {
	return v.value
}

func (v *NullableAnnulePartenaireToWalletModel) Set(val *AnnulePartenaireToWalletModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAnnulePartenaireToWalletModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAnnulePartenaireToWalletModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAnnulePartenaireToWalletModel(val *AnnulePartenaireToWalletModel) *NullableAnnulePartenaireToWalletModel {
	return &NullableAnnulePartenaireToWalletModel{value: val, isSet: true}
}

func (v NullableAnnulePartenaireToWalletModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAnnulePartenaireToWalletModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


