/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the ApisResponseV2AnnulationPartenaireToWalletResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApisResponseV2AnnulationPartenaireToWalletResponseV2{}

// ApisResponseV2AnnulationPartenaireToWalletResponseV2 struct for ApisResponseV2AnnulationPartenaireToWalletResponseV2
type ApisResponseV2AnnulationPartenaireToWalletResponseV2 struct {
	Status *string `json:"status,omitempty"`
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Data *AnnulationPartenaireToWalletResponseV2 `json:"data,omitempty"`
}

// NewApisResponseV2AnnulationPartenaireToWalletResponseV2 instantiates a new ApisResponseV2AnnulationPartenaireToWalletResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApisResponseV2AnnulationPartenaireToWalletResponseV2() *ApisResponseV2AnnulationPartenaireToWalletResponseV2 {
	this := ApisResponseV2AnnulationPartenaireToWalletResponseV2{}
	return &this
}

// NewApisResponseV2AnnulationPartenaireToWalletResponseV2WithDefaults instantiates a new ApisResponseV2AnnulationPartenaireToWalletResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApisResponseV2AnnulationPartenaireToWalletResponseV2WithDefaults() *ApisResponseV2AnnulationPartenaireToWalletResponseV2 {
	this := ApisResponseV2AnnulationPartenaireToWalletResponseV2{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) SetStatus(v string) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetData() AnnulationPartenaireToWalletResponseV2 {
	if o == nil || IsNil(o.Data) {
		var ret AnnulationPartenaireToWalletResponseV2
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) GetDataOk() (*AnnulationPartenaireToWalletResponseV2, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AnnulationPartenaireToWalletResponseV2 and assigns it to the Data field.
func (o *ApisResponseV2AnnulationPartenaireToWalletResponseV2) SetData(v AnnulationPartenaireToWalletResponseV2) {
	o.Data = &v
}

func (o ApisResponseV2AnnulationPartenaireToWalletResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApisResponseV2AnnulationPartenaireToWalletResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApisResponseV2AnnulationPartenaireToWalletResponseV2 struct {
	value *ApisResponseV2AnnulationPartenaireToWalletResponseV2
	isSet bool
}

func (v NullableApisResponseV2AnnulationPartenaireToWalletResponseV2) Get() *ApisResponseV2AnnulationPartenaireToWalletResponseV2 {
	return v.value
}

func (v *NullableApisResponseV2AnnulationPartenaireToWalletResponseV2) Set(val *ApisResponseV2AnnulationPartenaireToWalletResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableApisResponseV2AnnulationPartenaireToWalletResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableApisResponseV2AnnulationPartenaireToWalletResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApisResponseV2AnnulationPartenaireToWalletResponseV2(val *ApisResponseV2AnnulationPartenaireToWalletResponseV2) *NullableApisResponseV2AnnulationPartenaireToWalletResponseV2 {
	return &NullableApisResponseV2AnnulationPartenaireToWalletResponseV2{value: val, isSet: true}
}

func (v NullableApisResponseV2AnnulationPartenaireToWalletResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApisResponseV2AnnulationPartenaireToWalletResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


