/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the GetPartenaireToWalletResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPartenaireToWalletResponseV2{}

// GetPartenaireToWalletResponseV2 struct for GetPartenaireToWalletResponseV2
type GetPartenaireToWalletResponseV2 struct {
	Reference *string `json:"reference,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	AdresseIP *string `json:"adresseIP,omitempty"`
	Motif *string `json:"motif,omitempty"`
	MontantRecharge *float64 `json:"montantRecharge,omitempty"`
	FraisRecharge *float64 `json:"fraisRecharge,omitempty"`
	MontantTotalTransaction *float64 `json:"montantTotalTransaction,omitempty"`
	StatusTransaction *string `json:"statusTransaction,omitempty"`
	TypeTransaction *string `json:"typeTransaction,omitempty"`
	CompteClient *string `json:"compteClient,omitempty"`
	ComptePartenaire *string `json:"comptePartenaire,omitempty"`
	NomPartenaire *string `json:"nomPartenaire,omitempty"`
	PrenomPartenaire *string `json:"prenomPartenaire,omitempty"`
}

// NewGetPartenaireToWalletResponseV2 instantiates a new GetPartenaireToWalletResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPartenaireToWalletResponseV2() *GetPartenaireToWalletResponseV2 {
	this := GetPartenaireToWalletResponseV2{}
	return &this
}

// NewGetPartenaireToWalletResponseV2WithDefaults instantiates a new GetPartenaireToWalletResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPartenaireToWalletResponseV2WithDefaults() *GetPartenaireToWalletResponseV2 {
	this := GetPartenaireToWalletResponseV2{}
	return &this
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *GetPartenaireToWalletResponseV2) SetReference(v string) {
	o.Reference = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetPartenaireToWalletResponseV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetAdresseIP returns the AdresseIP field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetAdresseIP() string {
	if o == nil || IsNil(o.AdresseIP) {
		var ret string
		return ret
	}
	return *o.AdresseIP
}

// GetAdresseIPOk returns a tuple with the AdresseIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetAdresseIPOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIP) {
		return nil, false
	}
	return o.AdresseIP, true
}

// HasAdresseIP returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasAdresseIP() bool {
	if o != nil && !IsNil(o.AdresseIP) {
		return true
	}

	return false
}

// SetAdresseIP gets a reference to the given string and assigns it to the AdresseIP field.
func (o *GetPartenaireToWalletResponseV2) SetAdresseIP(v string) {
	o.AdresseIP = &v
}

// GetMotif returns the Motif field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetMotif() string {
	if o == nil || IsNil(o.Motif) {
		var ret string
		return ret
	}
	return *o.Motif
}

// GetMotifOk returns a tuple with the Motif field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetMotifOk() (*string, bool) {
	if o == nil || IsNil(o.Motif) {
		return nil, false
	}
	return o.Motif, true
}

// HasMotif returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasMotif() bool {
	if o != nil && !IsNil(o.Motif) {
		return true
	}

	return false
}

// SetMotif gets a reference to the given string and assigns it to the Motif field.
func (o *GetPartenaireToWalletResponseV2) SetMotif(v string) {
	o.Motif = &v
}

// GetMontantRecharge returns the MontantRecharge field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetMontantRecharge() float64 {
	if o == nil || IsNil(o.MontantRecharge) {
		var ret float64
		return ret
	}
	return *o.MontantRecharge
}

// GetMontantRechargeOk returns a tuple with the MontantRecharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetMontantRechargeOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantRecharge) {
		return nil, false
	}
	return o.MontantRecharge, true
}

// HasMontantRecharge returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasMontantRecharge() bool {
	if o != nil && !IsNil(o.MontantRecharge) {
		return true
	}

	return false
}

// SetMontantRecharge gets a reference to the given float64 and assigns it to the MontantRecharge field.
func (o *GetPartenaireToWalletResponseV2) SetMontantRecharge(v float64) {
	o.MontantRecharge = &v
}

// GetFraisRecharge returns the FraisRecharge field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetFraisRecharge() float64 {
	if o == nil || IsNil(o.FraisRecharge) {
		var ret float64
		return ret
	}
	return *o.FraisRecharge
}

// GetFraisRechargeOk returns a tuple with the FraisRecharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetFraisRechargeOk() (*float64, bool) {
	if o == nil || IsNil(o.FraisRecharge) {
		return nil, false
	}
	return o.FraisRecharge, true
}

// HasFraisRecharge returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasFraisRecharge() bool {
	if o != nil && !IsNil(o.FraisRecharge) {
		return true
	}

	return false
}

// SetFraisRecharge gets a reference to the given float64 and assigns it to the FraisRecharge field.
func (o *GetPartenaireToWalletResponseV2) SetFraisRecharge(v float64) {
	o.FraisRecharge = &v
}

// GetMontantTotalTransaction returns the MontantTotalTransaction field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetMontantTotalTransaction() float64 {
	if o == nil || IsNil(o.MontantTotalTransaction) {
		var ret float64
		return ret
	}
	return *o.MontantTotalTransaction
}

// GetMontantTotalTransactionOk returns a tuple with the MontantTotalTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetMontantTotalTransactionOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantTotalTransaction) {
		return nil, false
	}
	return o.MontantTotalTransaction, true
}

// HasMontantTotalTransaction returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasMontantTotalTransaction() bool {
	if o != nil && !IsNil(o.MontantTotalTransaction) {
		return true
	}

	return false
}

// SetMontantTotalTransaction gets a reference to the given float64 and assigns it to the MontantTotalTransaction field.
func (o *GetPartenaireToWalletResponseV2) SetMontantTotalTransaction(v float64) {
	o.MontantTotalTransaction = &v
}

// GetStatusTransaction returns the StatusTransaction field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetStatusTransaction() string {
	if o == nil || IsNil(o.StatusTransaction) {
		var ret string
		return ret
	}
	return *o.StatusTransaction
}

// GetStatusTransactionOk returns a tuple with the StatusTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetStatusTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.StatusTransaction) {
		return nil, false
	}
	return o.StatusTransaction, true
}

// HasStatusTransaction returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasStatusTransaction() bool {
	if o != nil && !IsNil(o.StatusTransaction) {
		return true
	}

	return false
}

// SetStatusTransaction gets a reference to the given string and assigns it to the StatusTransaction field.
func (o *GetPartenaireToWalletResponseV2) SetStatusTransaction(v string) {
	o.StatusTransaction = &v
}

// GetTypeTransaction returns the TypeTransaction field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetTypeTransaction() string {
	if o == nil || IsNil(o.TypeTransaction) {
		var ret string
		return ret
	}
	return *o.TypeTransaction
}

// GetTypeTransactionOk returns a tuple with the TypeTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetTypeTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeTransaction) {
		return nil, false
	}
	return o.TypeTransaction, true
}

// HasTypeTransaction returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasTypeTransaction() bool {
	if o != nil && !IsNil(o.TypeTransaction) {
		return true
	}

	return false
}

// SetTypeTransaction gets a reference to the given string and assigns it to the TypeTransaction field.
func (o *GetPartenaireToWalletResponseV2) SetTypeTransaction(v string) {
	o.TypeTransaction = &v
}

// GetCompteClient returns the CompteClient field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetCompteClient() string {
	if o == nil || IsNil(o.CompteClient) {
		var ret string
		return ret
	}
	return *o.CompteClient
}

// GetCompteClientOk returns a tuple with the CompteClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetCompteClientOk() (*string, bool) {
	if o == nil || IsNil(o.CompteClient) {
		return nil, false
	}
	return o.CompteClient, true
}

// HasCompteClient returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasCompteClient() bool {
	if o != nil && !IsNil(o.CompteClient) {
		return true
	}

	return false
}

// SetCompteClient gets a reference to the given string and assigns it to the CompteClient field.
func (o *GetPartenaireToWalletResponseV2) SetCompteClient(v string) {
	o.CompteClient = &v
}

// GetComptePartenaire returns the ComptePartenaire field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetComptePartenaire() string {
	if o == nil || IsNil(o.ComptePartenaire) {
		var ret string
		return ret
	}
	return *o.ComptePartenaire
}

// GetComptePartenaireOk returns a tuple with the ComptePartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetComptePartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.ComptePartenaire) {
		return nil, false
	}
	return o.ComptePartenaire, true
}

// HasComptePartenaire returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasComptePartenaire() bool {
	if o != nil && !IsNil(o.ComptePartenaire) {
		return true
	}

	return false
}

// SetComptePartenaire gets a reference to the given string and assigns it to the ComptePartenaire field.
func (o *GetPartenaireToWalletResponseV2) SetComptePartenaire(v string) {
	o.ComptePartenaire = &v
}

// GetNomPartenaire returns the NomPartenaire field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetNomPartenaire() string {
	if o == nil || IsNil(o.NomPartenaire) {
		var ret string
		return ret
	}
	return *o.NomPartenaire
}

// GetNomPartenaireOk returns a tuple with the NomPartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetNomPartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.NomPartenaire) {
		return nil, false
	}
	return o.NomPartenaire, true
}

// HasNomPartenaire returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasNomPartenaire() bool {
	if o != nil && !IsNil(o.NomPartenaire) {
		return true
	}

	return false
}

// SetNomPartenaire gets a reference to the given string and assigns it to the NomPartenaire field.
func (o *GetPartenaireToWalletResponseV2) SetNomPartenaire(v string) {
	o.NomPartenaire = &v
}

// GetPrenomPartenaire returns the PrenomPartenaire field value if set, zero value otherwise.
func (o *GetPartenaireToWalletResponseV2) GetPrenomPartenaire() string {
	if o == nil || IsNil(o.PrenomPartenaire) {
		var ret string
		return ret
	}
	return *o.PrenomPartenaire
}

// GetPrenomPartenaireOk returns a tuple with the PrenomPartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletResponseV2) GetPrenomPartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomPartenaire) {
		return nil, false
	}
	return o.PrenomPartenaire, true
}

// HasPrenomPartenaire returns a boolean if a field has been set.
func (o *GetPartenaireToWalletResponseV2) HasPrenomPartenaire() bool {
	if o != nil && !IsNil(o.PrenomPartenaire) {
		return true
	}

	return false
}

// SetPrenomPartenaire gets a reference to the given string and assigns it to the PrenomPartenaire field.
func (o *GetPartenaireToWalletResponseV2) SetPrenomPartenaire(v string) {
	o.PrenomPartenaire = &v
}

func (o GetPartenaireToWalletResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPartenaireToWalletResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.AdresseIP) {
		toSerialize["adresseIP"] = o.AdresseIP
	}
	if !IsNil(o.Motif) {
		toSerialize["motif"] = o.Motif
	}
	if !IsNil(o.MontantRecharge) {
		toSerialize["montantRecharge"] = o.MontantRecharge
	}
	if !IsNil(o.FraisRecharge) {
		toSerialize["fraisRecharge"] = o.FraisRecharge
	}
	if !IsNil(o.MontantTotalTransaction) {
		toSerialize["montantTotalTransaction"] = o.MontantTotalTransaction
	}
	if !IsNil(o.StatusTransaction) {
		toSerialize["statusTransaction"] = o.StatusTransaction
	}
	if !IsNil(o.TypeTransaction) {
		toSerialize["typeTransaction"] = o.TypeTransaction
	}
	if !IsNil(o.CompteClient) {
		toSerialize["compteClient"] = o.CompteClient
	}
	if !IsNil(o.ComptePartenaire) {
		toSerialize["comptePartenaire"] = o.ComptePartenaire
	}
	if !IsNil(o.NomPartenaire) {
		toSerialize["nomPartenaire"] = o.NomPartenaire
	}
	if !IsNil(o.PrenomPartenaire) {
		toSerialize["prenomPartenaire"] = o.PrenomPartenaire
	}
	return toSerialize, nil
}

type NullableGetPartenaireToWalletResponseV2 struct {
	value *GetPartenaireToWalletResponseV2
	isSet bool
}

func (v NullableGetPartenaireToWalletResponseV2) Get() *GetPartenaireToWalletResponseV2 {
	return v.value
}

func (v *NullableGetPartenaireToWalletResponseV2) Set(val *GetPartenaireToWalletResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPartenaireToWalletResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPartenaireToWalletResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPartenaireToWalletResponseV2(val *GetPartenaireToWalletResponseV2) *NullableGetPartenaireToWalletResponseV2 {
	return &NullableGetPartenaireToWalletResponseV2{value: val, isSet: true}
}

func (v NullableGetPartenaireToWalletResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPartenaireToWalletResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


