/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvoiInterPartenaireRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvoiInterPartenaireRequest{}

// EnvoiInterPartenaireRequest struct for EnvoiInterPartenaireRequest
type EnvoiInterPartenaireRequest struct {
	// Votre référence d'opération (idempotence).
	RequestId string `json:"requestId"`
	// Alias du partenaire destinataire (même organisation).
	PartenaireDestinataireAlias string `json:"partenaireDestinataireAlias"`
	// Libellé du compte destinataire (optionnel si unique).
	CompteDestinataire *string `json:"compteDestinataire,omitempty"`
	MontantTransaction float64 `json:"montantTransaction"`
	// fraisApars (défaut) ou fraisInclus.
	TypeFraisEnvoi *string `json:"typeFraisEnvoi,omitempty"`
	MotifTransaction *string `json:"motifTransaction,omitempty"`
	// Libellé du compte expéditeur (optionnel si unique).
	CompteExpediteur *string `json:"compteExpediteur,omitempty"`
}

type _EnvoiInterPartenaireRequest EnvoiInterPartenaireRequest

// NewEnvoiInterPartenaireRequest instantiates a new EnvoiInterPartenaireRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvoiInterPartenaireRequest(requestId string, partenaireDestinataireAlias string, montantTransaction float64) *EnvoiInterPartenaireRequest {
	this := EnvoiInterPartenaireRequest{}
	this.RequestId = requestId
	this.PartenaireDestinataireAlias = partenaireDestinataireAlias
	this.MontantTransaction = montantTransaction
	return &this
}

// NewEnvoiInterPartenaireRequestWithDefaults instantiates a new EnvoiInterPartenaireRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvoiInterPartenaireRequestWithDefaults() *EnvoiInterPartenaireRequest {
	this := EnvoiInterPartenaireRequest{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *EnvoiInterPartenaireRequest) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *EnvoiInterPartenaireRequest) SetRequestId(v string) {
	o.RequestId = v
}

// GetPartenaireDestinataireAlias returns the PartenaireDestinataireAlias field value
func (o *EnvoiInterPartenaireRequest) GetPartenaireDestinataireAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartenaireDestinataireAlias
}

// GetPartenaireDestinataireAliasOk returns a tuple with the PartenaireDestinataireAlias field value
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetPartenaireDestinataireAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartenaireDestinataireAlias, true
}

// SetPartenaireDestinataireAlias sets field value
func (o *EnvoiInterPartenaireRequest) SetPartenaireDestinataireAlias(v string) {
	o.PartenaireDestinataireAlias = v
}

// GetCompteDestinataire returns the CompteDestinataire field value if set, zero value otherwise.
func (o *EnvoiInterPartenaireRequest) GetCompteDestinataire() string {
	if o == nil || IsNil(o.CompteDestinataire) {
		var ret string
		return ret
	}
	return *o.CompteDestinataire
}

// GetCompteDestinataireOk returns a tuple with the CompteDestinataire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetCompteDestinataireOk() (*string, bool) {
	if o == nil || IsNil(o.CompteDestinataire) {
		return nil, false
	}
	return o.CompteDestinataire, true
}

// HasCompteDestinataire returns a boolean if a field has been set.
func (o *EnvoiInterPartenaireRequest) HasCompteDestinataire() bool {
	if o != nil && !IsNil(o.CompteDestinataire) {
		return true
	}

	return false
}

// SetCompteDestinataire gets a reference to the given string and assigns it to the CompteDestinataire field.
func (o *EnvoiInterPartenaireRequest) SetCompteDestinataire(v string) {
	o.CompteDestinataire = &v
}

// GetMontantTransaction returns the MontantTransaction field value
func (o *EnvoiInterPartenaireRequest) GetMontantTransaction() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MontantTransaction
}

// GetMontantTransactionOk returns a tuple with the MontantTransaction field value
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetMontantTransactionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MontantTransaction, true
}

// SetMontantTransaction sets field value
func (o *EnvoiInterPartenaireRequest) SetMontantTransaction(v float64) {
	o.MontantTransaction = v
}

// GetTypeFraisEnvoi returns the TypeFraisEnvoi field value if set, zero value otherwise.
func (o *EnvoiInterPartenaireRequest) GetTypeFraisEnvoi() string {
	if o == nil || IsNil(o.TypeFraisEnvoi) {
		var ret string
		return ret
	}
	return *o.TypeFraisEnvoi
}

// GetTypeFraisEnvoiOk returns a tuple with the TypeFraisEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetTypeFraisEnvoiOk() (*string, bool) {
	if o == nil || IsNil(o.TypeFraisEnvoi) {
		return nil, false
	}
	return o.TypeFraisEnvoi, true
}

// HasTypeFraisEnvoi returns a boolean if a field has been set.
func (o *EnvoiInterPartenaireRequest) HasTypeFraisEnvoi() bool {
	if o != nil && !IsNil(o.TypeFraisEnvoi) {
		return true
	}

	return false
}

// SetTypeFraisEnvoi gets a reference to the given string and assigns it to the TypeFraisEnvoi field.
func (o *EnvoiInterPartenaireRequest) SetTypeFraisEnvoi(v string) {
	o.TypeFraisEnvoi = &v
}

// GetMotifTransaction returns the MotifTransaction field value if set, zero value otherwise.
func (o *EnvoiInterPartenaireRequest) GetMotifTransaction() string {
	if o == nil || IsNil(o.MotifTransaction) {
		var ret string
		return ret
	}
	return *o.MotifTransaction
}

// GetMotifTransactionOk returns a tuple with the MotifTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetMotifTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.MotifTransaction) {
		return nil, false
	}
	return o.MotifTransaction, true
}

// HasMotifTransaction returns a boolean if a field has been set.
func (o *EnvoiInterPartenaireRequest) HasMotifTransaction() bool {
	if o != nil && !IsNil(o.MotifTransaction) {
		return true
	}

	return false
}

// SetMotifTransaction gets a reference to the given string and assigns it to the MotifTransaction field.
func (o *EnvoiInterPartenaireRequest) SetMotifTransaction(v string) {
	o.MotifTransaction = &v
}

// GetCompteExpediteur returns the CompteExpediteur field value if set, zero value otherwise.
func (o *EnvoiInterPartenaireRequest) GetCompteExpediteur() string {
	if o == nil || IsNil(o.CompteExpediteur) {
		var ret string
		return ret
	}
	return *o.CompteExpediteur
}

// GetCompteExpediteurOk returns a tuple with the CompteExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnvoiInterPartenaireRequest) GetCompteExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.CompteExpediteur) {
		return nil, false
	}
	return o.CompteExpediteur, true
}

// HasCompteExpediteur returns a boolean if a field has been set.
func (o *EnvoiInterPartenaireRequest) HasCompteExpediteur() bool {
	if o != nil && !IsNil(o.CompteExpediteur) {
		return true
	}

	return false
}

// SetCompteExpediteur gets a reference to the given string and assigns it to the CompteExpediteur field.
func (o *EnvoiInterPartenaireRequest) SetCompteExpediteur(v string) {
	o.CompteExpediteur = &v
}

func (o EnvoiInterPartenaireRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvoiInterPartenaireRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	toSerialize["partenaireDestinataireAlias"] = o.PartenaireDestinataireAlias
	if !IsNil(o.CompteDestinataire) {
		toSerialize["compteDestinataire"] = o.CompteDestinataire
	}
	toSerialize["montantTransaction"] = o.MontantTransaction
	if !IsNil(o.TypeFraisEnvoi) {
		toSerialize["typeFraisEnvoi"] = o.TypeFraisEnvoi
	}
	if !IsNil(o.MotifTransaction) {
		toSerialize["motifTransaction"] = o.MotifTransaction
	}
	if !IsNil(o.CompteExpediteur) {
		toSerialize["compteExpediteur"] = o.CompteExpediteur
	}
	return toSerialize, nil
}

func (o *EnvoiInterPartenaireRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
		"partenaireDestinataireAlias",
		"montantTransaction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvoiInterPartenaireRequest := _EnvoiInterPartenaireRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvoiInterPartenaireRequest)

	if err != nil {
		return err
	}

	*o = EnvoiInterPartenaireRequest(varEnvoiInterPartenaireRequest)

	return err
}

type NullableEnvoiInterPartenaireRequest struct {
	value *EnvoiInterPartenaireRequest
	isSet bool
}

func (v NullableEnvoiInterPartenaireRequest) Get() *EnvoiInterPartenaireRequest {
	return v.value
}

func (v *NullableEnvoiInterPartenaireRequest) Set(val *EnvoiInterPartenaireRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvoiInterPartenaireRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvoiInterPartenaireRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvoiInterPartenaireRequest(val *EnvoiInterPartenaireRequest) *NullableEnvoiInterPartenaireRequest {
	return &NullableEnvoiInterPartenaireRequest{value: val, isSet: true}
}

func (v NullableEnvoiInterPartenaireRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvoiInterPartenaireRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


