/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetPartenaireToWalletModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPartenaireToWalletModel{}

// GetPartenaireToWalletModel struct for GetPartenaireToWalletModel
type GetPartenaireToWalletModel struct {
	RequestId string `json:"requestId"`
	// Facultatif : absent, la recharge est retrouvée par le seul requestId (reprise après un timeout à la création).
	CodeRecharge *string `json:"codeRecharge,omitempty"`
}

type _GetPartenaireToWalletModel GetPartenaireToWalletModel

// NewGetPartenaireToWalletModel instantiates a new GetPartenaireToWalletModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPartenaireToWalletModel(requestId string) *GetPartenaireToWalletModel {
	this := GetPartenaireToWalletModel{}
	this.RequestId = requestId
	return &this
}

// NewGetPartenaireToWalletModelWithDefaults instantiates a new GetPartenaireToWalletModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPartenaireToWalletModelWithDefaults() *GetPartenaireToWalletModel {
	this := GetPartenaireToWalletModel{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *GetPartenaireToWalletModel) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletModel) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *GetPartenaireToWalletModel) SetRequestId(v string) {
	o.RequestId = v
}

// GetCodeRecharge returns the CodeRecharge field value if set, zero value otherwise.
func (o *GetPartenaireToWalletModel) GetCodeRecharge() string {
	if o == nil || IsNil(o.CodeRecharge) {
		var ret string
		return ret
	}
	return *o.CodeRecharge
}

// GetCodeRechargeOk returns a tuple with the CodeRecharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPartenaireToWalletModel) GetCodeRechargeOk() (*string, bool) {
	if o == nil || IsNil(o.CodeRecharge) {
		return nil, false
	}
	return o.CodeRecharge, true
}

// HasCodeRecharge returns a boolean if a field has been set.
func (o *GetPartenaireToWalletModel) HasCodeRecharge() bool {
	if o != nil && !IsNil(o.CodeRecharge) {
		return true
	}

	return false
}

// SetCodeRecharge gets a reference to the given string and assigns it to the CodeRecharge field.
func (o *GetPartenaireToWalletModel) SetCodeRecharge(v string) {
	o.CodeRecharge = &v
}

func (o GetPartenaireToWalletModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPartenaireToWalletModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["requestId"] = o.RequestId
	if !IsNil(o.CodeRecharge) {
		toSerialize["codeRecharge"] = o.CodeRecharge
	}
	return toSerialize, nil
}

func (o *GetPartenaireToWalletModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"requestId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPartenaireToWalletModel := _GetPartenaireToWalletModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPartenaireToWalletModel)

	if err != nil {
		return err
	}

	*o = GetPartenaireToWalletModel(varGetPartenaireToWalletModel)

	return err
}

type NullableGetPartenaireToWalletModel struct {
	value *GetPartenaireToWalletModel
	isSet bool
}

func (v NullableGetPartenaireToWalletModel) Get() *GetPartenaireToWalletModel {
	return v.value
}

func (v *NullableGetPartenaireToWalletModel) Set(val *GetPartenaireToWalletModel) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPartenaireToWalletModel) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPartenaireToWalletModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPartenaireToWalletModel(val *GetPartenaireToWalletModel) *NullableGetPartenaireToWalletModel {
	return &NullableGetPartenaireToWalletModel{value: val, isSet: true}
}

func (v NullableGetPartenaireToWalletModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPartenaireToWalletModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


