/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"time"
)

// checks if the AddAchatEnligneResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAchatEnligneResponseV2{}

// AddAchatEnligneResponseV2 struct for AddAchatEnligneResponseV2
type AddAchatEnligneResponseV2 struct {
	PublicId *string `json:"publicId,omitempty"`
	PhoneClient *string `json:"phoneClient,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	AdresseIP *string `json:"adresseIP,omitempty"`
	CodeAchat *string `json:"codeAchat,omitempty"`
	DescriptionAchat *string `json:"descriptionAchat,omitempty"`
	Montant *float64 `json:"montant,omitempty"`
	StatusTransaction *string `json:"statusTransaction,omitempty"`
	TypeTransaction *string `json:"typeTransaction,omitempty"`
	ComptePartenaire *string `json:"ComptePartenaire,omitempty"`
	NomPartenaire *string `json:"nomPartenaire,omitempty"`
	PrenomPartenaire *string `json:"prenomPartenaire,omitempty"`
	DateTransaction *time.Time `json:"dateTransaction,omitempty"`
	// Lien de règlement à transmettre à l'acheteur, dérivé du codeAchat. Nul tant que la page de paiement publique n'est pas en service : un champ absent vaut mieux qu'un lien qui ne s'ouvre pas. Ne pas le reconstruire à la main.
	UrlPaiement *string `json:"urlPaiement,omitempty"`
}

// NewAddAchatEnligneResponseV2 instantiates a new AddAchatEnligneResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAchatEnligneResponseV2() *AddAchatEnligneResponseV2 {
	this := AddAchatEnligneResponseV2{}
	return &this
}

// NewAddAchatEnligneResponseV2WithDefaults instantiates a new AddAchatEnligneResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAchatEnligneResponseV2WithDefaults() *AddAchatEnligneResponseV2 {
	this := AddAchatEnligneResponseV2{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetPublicId() string {
	if o == nil || IsNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetPublicIdOk() (*string, bool) {
	if o == nil || IsNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasPublicId() bool {
	if o != nil && !IsNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *AddAchatEnligneResponseV2) SetPublicId(v string) {
	o.PublicId = &v
}

// GetPhoneClient returns the PhoneClient field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetPhoneClient() string {
	if o == nil || IsNil(o.PhoneClient) {
		var ret string
		return ret
	}
	return *o.PhoneClient
}

// GetPhoneClientOk returns a tuple with the PhoneClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetPhoneClientOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneClient) {
		return nil, false
	}
	return o.PhoneClient, true
}

// HasPhoneClient returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasPhoneClient() bool {
	if o != nil && !IsNil(o.PhoneClient) {
		return true
	}

	return false
}

// SetPhoneClient gets a reference to the given string and assigns it to the PhoneClient field.
func (o *AddAchatEnligneResponseV2) SetPhoneClient(v string) {
	o.PhoneClient = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *AddAchatEnligneResponseV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetAdresseIP returns the AdresseIP field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetAdresseIP() string {
	if o == nil || IsNil(o.AdresseIP) {
		var ret string
		return ret
	}
	return *o.AdresseIP
}

// GetAdresseIPOk returns a tuple with the AdresseIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetAdresseIPOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIP) {
		return nil, false
	}
	return o.AdresseIP, true
}

// HasAdresseIP returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasAdresseIP() bool {
	if o != nil && !IsNil(o.AdresseIP) {
		return true
	}

	return false
}

// SetAdresseIP gets a reference to the given string and assigns it to the AdresseIP field.
func (o *AddAchatEnligneResponseV2) SetAdresseIP(v string) {
	o.AdresseIP = &v
}

// GetCodeAchat returns the CodeAchat field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetCodeAchat() string {
	if o == nil || IsNil(o.CodeAchat) {
		var ret string
		return ret
	}
	return *o.CodeAchat
}

// GetCodeAchatOk returns a tuple with the CodeAchat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetCodeAchatOk() (*string, bool) {
	if o == nil || IsNil(o.CodeAchat) {
		return nil, false
	}
	return o.CodeAchat, true
}

// HasCodeAchat returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasCodeAchat() bool {
	if o != nil && !IsNil(o.CodeAchat) {
		return true
	}

	return false
}

// SetCodeAchat gets a reference to the given string and assigns it to the CodeAchat field.
func (o *AddAchatEnligneResponseV2) SetCodeAchat(v string) {
	o.CodeAchat = &v
}

// GetDescriptionAchat returns the DescriptionAchat field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetDescriptionAchat() string {
	if o == nil || IsNil(o.DescriptionAchat) {
		var ret string
		return ret
	}
	return *o.DescriptionAchat
}

// GetDescriptionAchatOk returns a tuple with the DescriptionAchat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetDescriptionAchatOk() (*string, bool) {
	if o == nil || IsNil(o.DescriptionAchat) {
		return nil, false
	}
	return o.DescriptionAchat, true
}

// HasDescriptionAchat returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasDescriptionAchat() bool {
	if o != nil && !IsNil(o.DescriptionAchat) {
		return true
	}

	return false
}

// SetDescriptionAchat gets a reference to the given string and assigns it to the DescriptionAchat field.
func (o *AddAchatEnligneResponseV2) SetDescriptionAchat(v string) {
	o.DescriptionAchat = &v
}

// GetMontant returns the Montant field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetMontant() float64 {
	if o == nil || IsNil(o.Montant) {
		var ret float64
		return ret
	}
	return *o.Montant
}

// GetMontantOk returns a tuple with the Montant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetMontantOk() (*float64, bool) {
	if o == nil || IsNil(o.Montant) {
		return nil, false
	}
	return o.Montant, true
}

// HasMontant returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasMontant() bool {
	if o != nil && !IsNil(o.Montant) {
		return true
	}

	return false
}

// SetMontant gets a reference to the given float64 and assigns it to the Montant field.
func (o *AddAchatEnligneResponseV2) SetMontant(v float64) {
	o.Montant = &v
}

// GetStatusTransaction returns the StatusTransaction field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetStatusTransaction() string {
	if o == nil || IsNil(o.StatusTransaction) {
		var ret string
		return ret
	}
	return *o.StatusTransaction
}

// GetStatusTransactionOk returns a tuple with the StatusTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetStatusTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.StatusTransaction) {
		return nil, false
	}
	return o.StatusTransaction, true
}

// HasStatusTransaction returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasStatusTransaction() bool {
	if o != nil && !IsNil(o.StatusTransaction) {
		return true
	}

	return false
}

// SetStatusTransaction gets a reference to the given string and assigns it to the StatusTransaction field.
func (o *AddAchatEnligneResponseV2) SetStatusTransaction(v string) {
	o.StatusTransaction = &v
}

// GetTypeTransaction returns the TypeTransaction field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetTypeTransaction() string {
	if o == nil || IsNil(o.TypeTransaction) {
		var ret string
		return ret
	}
	return *o.TypeTransaction
}

// GetTypeTransactionOk returns a tuple with the TypeTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetTypeTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeTransaction) {
		return nil, false
	}
	return o.TypeTransaction, true
}

// HasTypeTransaction returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasTypeTransaction() bool {
	if o != nil && !IsNil(o.TypeTransaction) {
		return true
	}

	return false
}

// SetTypeTransaction gets a reference to the given string and assigns it to the TypeTransaction field.
func (o *AddAchatEnligneResponseV2) SetTypeTransaction(v string) {
	o.TypeTransaction = &v
}

// GetComptePartenaire returns the ComptePartenaire field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetComptePartenaire() string {
	if o == nil || IsNil(o.ComptePartenaire) {
		var ret string
		return ret
	}
	return *o.ComptePartenaire
}

// GetComptePartenaireOk returns a tuple with the ComptePartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetComptePartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.ComptePartenaire) {
		return nil, false
	}
	return o.ComptePartenaire, true
}

// HasComptePartenaire returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasComptePartenaire() bool {
	if o != nil && !IsNil(o.ComptePartenaire) {
		return true
	}

	return false
}

// SetComptePartenaire gets a reference to the given string and assigns it to the ComptePartenaire field.
func (o *AddAchatEnligneResponseV2) SetComptePartenaire(v string) {
	o.ComptePartenaire = &v
}

// GetNomPartenaire returns the NomPartenaire field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetNomPartenaire() string {
	if o == nil || IsNil(o.NomPartenaire) {
		var ret string
		return ret
	}
	return *o.NomPartenaire
}

// GetNomPartenaireOk returns a tuple with the NomPartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetNomPartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.NomPartenaire) {
		return nil, false
	}
	return o.NomPartenaire, true
}

// HasNomPartenaire returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasNomPartenaire() bool {
	if o != nil && !IsNil(o.NomPartenaire) {
		return true
	}

	return false
}

// SetNomPartenaire gets a reference to the given string and assigns it to the NomPartenaire field.
func (o *AddAchatEnligneResponseV2) SetNomPartenaire(v string) {
	o.NomPartenaire = &v
}

// GetPrenomPartenaire returns the PrenomPartenaire field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetPrenomPartenaire() string {
	if o == nil || IsNil(o.PrenomPartenaire) {
		var ret string
		return ret
	}
	return *o.PrenomPartenaire
}

// GetPrenomPartenaireOk returns a tuple with the PrenomPartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetPrenomPartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomPartenaire) {
		return nil, false
	}
	return o.PrenomPartenaire, true
}

// HasPrenomPartenaire returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasPrenomPartenaire() bool {
	if o != nil && !IsNil(o.PrenomPartenaire) {
		return true
	}

	return false
}

// SetPrenomPartenaire gets a reference to the given string and assigns it to the PrenomPartenaire field.
func (o *AddAchatEnligneResponseV2) SetPrenomPartenaire(v string) {
	o.PrenomPartenaire = &v
}

// GetDateTransaction returns the DateTransaction field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetDateTransaction() time.Time {
	if o == nil || IsNil(o.DateTransaction) {
		var ret time.Time
		return ret
	}
	return *o.DateTransaction
}

// GetDateTransactionOk returns a tuple with the DateTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetDateTransactionOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateTransaction) {
		return nil, false
	}
	return o.DateTransaction, true
}

// HasDateTransaction returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasDateTransaction() bool {
	if o != nil && !IsNil(o.DateTransaction) {
		return true
	}

	return false
}

// SetDateTransaction gets a reference to the given time.Time and assigns it to the DateTransaction field.
func (o *AddAchatEnligneResponseV2) SetDateTransaction(v time.Time) {
	o.DateTransaction = &v
}

// GetUrlPaiement returns the UrlPaiement field value if set, zero value otherwise.
func (o *AddAchatEnligneResponseV2) GetUrlPaiement() string {
	if o == nil || IsNil(o.UrlPaiement) {
		var ret string
		return ret
	}
	return *o.UrlPaiement
}

// GetUrlPaiementOk returns a tuple with the UrlPaiement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAchatEnligneResponseV2) GetUrlPaiementOk() (*string, bool) {
	if o == nil || IsNil(o.UrlPaiement) {
		return nil, false
	}
	return o.UrlPaiement, true
}

// HasUrlPaiement returns a boolean if a field has been set.
func (o *AddAchatEnligneResponseV2) HasUrlPaiement() bool {
	if o != nil && !IsNil(o.UrlPaiement) {
		return true
	}

	return false
}

// SetUrlPaiement gets a reference to the given string and assigns it to the UrlPaiement field.
func (o *AddAchatEnligneResponseV2) SetUrlPaiement(v string) {
	o.UrlPaiement = &v
}

func (o AddAchatEnligneResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAchatEnligneResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !IsNil(o.PhoneClient) {
		toSerialize["phoneClient"] = o.PhoneClient
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.AdresseIP) {
		toSerialize["adresseIP"] = o.AdresseIP
	}
	if !IsNil(o.CodeAchat) {
		toSerialize["codeAchat"] = o.CodeAchat
	}
	if !IsNil(o.DescriptionAchat) {
		toSerialize["descriptionAchat"] = o.DescriptionAchat
	}
	if !IsNil(o.Montant) {
		toSerialize["montant"] = o.Montant
	}
	if !IsNil(o.StatusTransaction) {
		toSerialize["statusTransaction"] = o.StatusTransaction
	}
	if !IsNil(o.TypeTransaction) {
		toSerialize["typeTransaction"] = o.TypeTransaction
	}
	if !IsNil(o.ComptePartenaire) {
		toSerialize["ComptePartenaire"] = o.ComptePartenaire
	}
	if !IsNil(o.NomPartenaire) {
		toSerialize["nomPartenaire"] = o.NomPartenaire
	}
	if !IsNil(o.PrenomPartenaire) {
		toSerialize["prenomPartenaire"] = o.PrenomPartenaire
	}
	if !IsNil(o.DateTransaction) {
		toSerialize["dateTransaction"] = o.DateTransaction
	}
	if !IsNil(o.UrlPaiement) {
		toSerialize["urlPaiement"] = o.UrlPaiement
	}
	return toSerialize, nil
}

type NullableAddAchatEnligneResponseV2 struct {
	value *AddAchatEnligneResponseV2
	isSet bool
}

func (v NullableAddAchatEnligneResponseV2) Get() *AddAchatEnligneResponseV2 {
	return v.value
}

func (v *NullableAddAchatEnligneResponseV2) Set(val *AddAchatEnligneResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAchatEnligneResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAchatEnligneResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAchatEnligneResponseV2(val *AddAchatEnligneResponseV2) *NullableAddAchatEnligneResponseV2 {
	return &NullableAddAchatEnligneResponseV2{value: val, isSet: true}
}

func (v NullableAddAchatEnligneResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAchatEnligneResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


