/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the ApisResponseV2ModelEditEnvoieRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApisResponseV2ModelEditEnvoieRequest{}

// ApisResponseV2ModelEditEnvoieRequest struct for ApisResponseV2ModelEditEnvoieRequest
type ApisResponseV2ModelEditEnvoieRequest struct {
	Status *string `json:"status,omitempty"`
	Code *int32 `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
	Data *ModelEditEnvoieRequest `json:"data,omitempty"`
}

// NewApisResponseV2ModelEditEnvoieRequest instantiates a new ApisResponseV2ModelEditEnvoieRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApisResponseV2ModelEditEnvoieRequest() *ApisResponseV2ModelEditEnvoieRequest {
	this := ApisResponseV2ModelEditEnvoieRequest{}
	return &this
}

// NewApisResponseV2ModelEditEnvoieRequestWithDefaults instantiates a new ApisResponseV2ModelEditEnvoieRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApisResponseV2ModelEditEnvoieRequestWithDefaults() *ApisResponseV2ModelEditEnvoieRequest {
	this := ApisResponseV2ModelEditEnvoieRequest{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ApisResponseV2ModelEditEnvoieRequest) SetStatus(v string) {
	o.Status = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *ApisResponseV2ModelEditEnvoieRequest) SetCode(v int32) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ApisResponseV2ModelEditEnvoieRequest) SetMessage(v string) {
	o.Message = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetData() ModelEditEnvoieRequest {
	if o == nil || IsNil(o.Data) {
		var ret ModelEditEnvoieRequest
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) GetDataOk() (*ModelEditEnvoieRequest, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApisResponseV2ModelEditEnvoieRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ModelEditEnvoieRequest and assigns it to the Data field.
func (o *ApisResponseV2ModelEditEnvoieRequest) SetData(v ModelEditEnvoieRequest) {
	o.Data = &v
}

func (o ApisResponseV2ModelEditEnvoieRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApisResponseV2ModelEditEnvoieRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableApisResponseV2ModelEditEnvoieRequest struct {
	value *ApisResponseV2ModelEditEnvoieRequest
	isSet bool
}

func (v NullableApisResponseV2ModelEditEnvoieRequest) Get() *ApisResponseV2ModelEditEnvoieRequest {
	return v.value
}

func (v *NullableApisResponseV2ModelEditEnvoieRequest) Set(val *ApisResponseV2ModelEditEnvoieRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApisResponseV2ModelEditEnvoieRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApisResponseV2ModelEditEnvoieRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApisResponseV2ModelEditEnvoieRequest(val *ApisResponseV2ModelEditEnvoieRequest) *NullableApisResponseV2ModelEditEnvoieRequest {
	return &NullableApisResponseV2ModelEditEnvoieRequest{value: val, isSet: true}
}

func (v NullableApisResponseV2ModelEditEnvoieRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApisResponseV2ModelEditEnvoieRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


