/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the IndicatifResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndicatifResponse{}

// IndicatifResponse struct for IndicatifResponse
type IndicatifResponse struct {
	Pays *string `json:"pays,omitempty"`
	Indicatif *string `json:"indicatif,omitempty"`
}

// NewIndicatifResponse instantiates a new IndicatifResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndicatifResponse() *IndicatifResponse {
	this := IndicatifResponse{}
	return &this
}

// NewIndicatifResponseWithDefaults instantiates a new IndicatifResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndicatifResponseWithDefaults() *IndicatifResponse {
	this := IndicatifResponse{}
	return &this
}

// GetPays returns the Pays field value if set, zero value otherwise.
func (o *IndicatifResponse) GetPays() string {
	if o == nil || IsNil(o.Pays) {
		var ret string
		return ret
	}
	return *o.Pays
}

// GetPaysOk returns a tuple with the Pays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndicatifResponse) GetPaysOk() (*string, bool) {
	if o == nil || IsNil(o.Pays) {
		return nil, false
	}
	return o.Pays, true
}

// HasPays returns a boolean if a field has been set.
func (o *IndicatifResponse) HasPays() bool {
	if o != nil && !IsNil(o.Pays) {
		return true
	}

	return false
}

// SetPays gets a reference to the given string and assigns it to the Pays field.
func (o *IndicatifResponse) SetPays(v string) {
	o.Pays = &v
}

// GetIndicatif returns the Indicatif field value if set, zero value otherwise.
func (o *IndicatifResponse) GetIndicatif() string {
	if o == nil || IsNil(o.Indicatif) {
		var ret string
		return ret
	}
	return *o.Indicatif
}

// GetIndicatifOk returns a tuple with the Indicatif field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndicatifResponse) GetIndicatifOk() (*string, bool) {
	if o == nil || IsNil(o.Indicatif) {
		return nil, false
	}
	return o.Indicatif, true
}

// HasIndicatif returns a boolean if a field has been set.
func (o *IndicatifResponse) HasIndicatif() bool {
	if o != nil && !IsNil(o.Indicatif) {
		return true
	}

	return false
}

// SetIndicatif gets a reference to the given string and assigns it to the Indicatif field.
func (o *IndicatifResponse) SetIndicatif(v string) {
	o.Indicatif = &v
}

func (o IndicatifResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndicatifResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Pays) {
		toSerialize["pays"] = o.Pays
	}
	if !IsNil(o.Indicatif) {
		toSerialize["indicatif"] = o.Indicatif
	}
	return toSerialize, nil
}

type NullableIndicatifResponse struct {
	value *IndicatifResponse
	isSet bool
}

func (v NullableIndicatifResponse) Get() *IndicatifResponse {
	return v.value
}

func (v *NullableIndicatifResponse) Set(val *IndicatifResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIndicatifResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIndicatifResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndicatifResponse(val *IndicatifResponse) *NullableIndicatifResponse {
	return &NullableIndicatifResponse{value: val, isSet: true}
}

func (v NullableIndicatifResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndicatifResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


