/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PartenaireToWalletFraisRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartenaireToWalletFraisRequest{}

// PartenaireToWalletFraisRequest Requete de calcul des frais Partenaire vers Wallet (P2W).
type PartenaireToWalletFraisRequest struct {
	// Numero du client MyNITA (wallet cible).
	PhoneClient string `json:"phoneClient"`
	// Montant de la recharge.
	MontantTransaction float64 `json:"montantTransaction"`
}

type _PartenaireToWalletFraisRequest PartenaireToWalletFraisRequest

// NewPartenaireToWalletFraisRequest instantiates a new PartenaireToWalletFraisRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartenaireToWalletFraisRequest(phoneClient string, montantTransaction float64) *PartenaireToWalletFraisRequest {
	this := PartenaireToWalletFraisRequest{}
	this.PhoneClient = phoneClient
	this.MontantTransaction = montantTransaction
	return &this
}

// NewPartenaireToWalletFraisRequestWithDefaults instantiates a new PartenaireToWalletFraisRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartenaireToWalletFraisRequestWithDefaults() *PartenaireToWalletFraisRequest {
	this := PartenaireToWalletFraisRequest{}
	return &this
}

// GetPhoneClient returns the PhoneClient field value
func (o *PartenaireToWalletFraisRequest) GetPhoneClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneClient
}

// GetPhoneClientOk returns a tuple with the PhoneClient field value
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletFraisRequest) GetPhoneClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneClient, true
}

// SetPhoneClient sets field value
func (o *PartenaireToWalletFraisRequest) SetPhoneClient(v string) {
	o.PhoneClient = v
}

// GetMontantTransaction returns the MontantTransaction field value
func (o *PartenaireToWalletFraisRequest) GetMontantTransaction() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MontantTransaction
}

// GetMontantTransactionOk returns a tuple with the MontantTransaction field value
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletFraisRequest) GetMontantTransactionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MontantTransaction, true
}

// SetMontantTransaction sets field value
func (o *PartenaireToWalletFraisRequest) SetMontantTransaction(v float64) {
	o.MontantTransaction = v
}

func (o PartenaireToWalletFraisRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartenaireToWalletFraisRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["phoneClient"] = o.PhoneClient
	toSerialize["montantTransaction"] = o.MontantTransaction
	return toSerialize, nil
}

func (o *PartenaireToWalletFraisRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"phoneClient",
		"montantTransaction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartenaireToWalletFraisRequest := _PartenaireToWalletFraisRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartenaireToWalletFraisRequest)

	if err != nil {
		return err
	}

	*o = PartenaireToWalletFraisRequest(varPartenaireToWalletFraisRequest)

	return err
}

type NullablePartenaireToWalletFraisRequest struct {
	value *PartenaireToWalletFraisRequest
	isSet bool
}

func (v NullablePartenaireToWalletFraisRequest) Get() *PartenaireToWalletFraisRequest {
	return v.value
}

func (v *NullablePartenaireToWalletFraisRequest) Set(val *PartenaireToWalletFraisRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePartenaireToWalletFraisRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePartenaireToWalletFraisRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartenaireToWalletFraisRequest(val *PartenaireToWalletFraisRequest) *NullablePartenaireToWalletFraisRequest {
	return &NullablePartenaireToWalletFraisRequest{value: val, isSet: true}
}

func (v NullablePartenaireToWalletFraisRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartenaireToWalletFraisRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


