/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PartenaireToCashDtoV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartenaireToCashDtoV2{}

// PartenaireToCashDtoV2 struct for PartenaireToCashDtoV2
type PartenaireToCashDtoV2 struct {
	Nom string `json:"nom" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]{1,100}$"`
	Prenom string `json:"prenom" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]{1,100}$"`
	Indicatif string `json:"indicatif" validate:"regexp=^\\\\d{2,6}$"`
	Numero string `json:"numero" validate:"regexp=^\\\\d{4,15}$"`
	DateNaissance *time.Time `json:"dateNaissance,omitempty"`
	LieuNaissance *string `json:"lieuNaissance,omitempty" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-,]*$"`
	SituationMatrimoniale *string `json:"situationMatrimoniale,omitempty"`
	Genre *string `json:"genre,omitempty" validate:"regexp=^[A-Za-z]*$"`
	Profession *string `json:"profession,omitempty" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-,]*$"`
	Adresse *string `json:"adresse,omitempty"`
	VilleResidence *string `json:"villeResidence,omitempty" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]*$"`
	PaysResidence *string `json:"paysResidence,omitempty" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]*$"`
	TypePiece *string `json:"typePiece,omitempty"`
	NumeroPiece *string `json:"numeroPiece,omitempty" validate:"regexp=^[a-zA-Z0-9\\\\s\\\\-\\/]*$"`
	DateDelivrance *time.Time `json:"dateDelivrance,omitempty"`
	LieuDelivrance *string `json:"lieuDelivrance,omitempty" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-,]*$"`
	Autorite *string `json:"autorite,omitempty" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]*$"`
	PhotoPieceIdentiteRecto *string `json:"photoPieceIdentiteRecto,omitempty"`
	PhotoPieceIdentiteVerso *string `json:"photoPieceIdentiteVerso,omitempty"`
	PhotoIdentite *string `json:"photoIdentite,omitempty"`
	RequestId string `json:"requestId" validate:"regexp=^[a-zA-Z0-9_\\\\-]{4,100}$"`
	FraisInclus bool `json:"fraisInclus"`
	Montant float64 `json:"montant"`
	VilleDestination string `json:"villeDestination" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]{1,100}$"`
	NomDestinataire string `json:"nomDestinataire" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]{1,100}$"`
	PrenomDestinataire string `json:"prenomDestinataire" validate:"regexp=^[\\\\p{L}\\\\s'.\\\\-]{1,100}$"`
	IndicatifDestinataire string `json:"indicatifDestinataire" validate:"regexp=^\\\\d{2,6}$"`
	NumeroDestinataire string `json:"numeroDestinataire" validate:"regexp=^\\\\d{4,15}$"`
	MotifTransaction *string `json:"motifTransaction,omitempty"`
	AdresseIp *string `json:"adresseIp,omitempty" validate:"regexp=^((\\\\d{1,3}\\\\.){3}\\\\d{1,3}|[0-9a-fA-F:]{3,39})?$"`
	UrlCallback *string `json:"urlCallback,omitempty"`
}

type _PartenaireToCashDtoV2 PartenaireToCashDtoV2

// NewPartenaireToCashDtoV2 instantiates a new PartenaireToCashDtoV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartenaireToCashDtoV2(nom string, prenom string, indicatif string, numero string, requestId string, fraisInclus bool, montant float64, villeDestination string, nomDestinataire string, prenomDestinataire string, indicatifDestinataire string, numeroDestinataire string) *PartenaireToCashDtoV2 {
	this := PartenaireToCashDtoV2{}
	this.Nom = nom
	this.Prenom = prenom
	this.Indicatif = indicatif
	this.Numero = numero
	this.RequestId = requestId
	this.FraisInclus = fraisInclus
	this.Montant = montant
	this.VilleDestination = villeDestination
	this.NomDestinataire = nomDestinataire
	this.PrenomDestinataire = prenomDestinataire
	this.IndicatifDestinataire = indicatifDestinataire
	this.NumeroDestinataire = numeroDestinataire
	return &this
}

// NewPartenaireToCashDtoV2WithDefaults instantiates a new PartenaireToCashDtoV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartenaireToCashDtoV2WithDefaults() *PartenaireToCashDtoV2 {
	this := PartenaireToCashDtoV2{}
	return &this
}

// GetNom returns the Nom field value
func (o *PartenaireToCashDtoV2) GetNom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Nom
}

// GetNomOk returns a tuple with the Nom field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetNomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Nom, true
}

// SetNom sets field value
func (o *PartenaireToCashDtoV2) SetNom(v string) {
	o.Nom = v
}

// GetPrenom returns the Prenom field value
func (o *PartenaireToCashDtoV2) GetPrenom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prenom
}

// GetPrenomOk returns a tuple with the Prenom field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetPrenomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prenom, true
}

// SetPrenom sets field value
func (o *PartenaireToCashDtoV2) SetPrenom(v string) {
	o.Prenom = v
}

// GetIndicatif returns the Indicatif field value
func (o *PartenaireToCashDtoV2) GetIndicatif() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Indicatif
}

// GetIndicatifOk returns a tuple with the Indicatif field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetIndicatifOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Indicatif, true
}

// SetIndicatif sets field value
func (o *PartenaireToCashDtoV2) SetIndicatif(v string) {
	o.Indicatif = v
}

// GetNumero returns the Numero field value
func (o *PartenaireToCashDtoV2) GetNumero() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Numero
}

// GetNumeroOk returns a tuple with the Numero field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetNumeroOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Numero, true
}

// SetNumero sets field value
func (o *PartenaireToCashDtoV2) SetNumero(v string) {
	o.Numero = v
}

// GetDateNaissance returns the DateNaissance field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetDateNaissance() time.Time {
	if o == nil || IsNil(o.DateNaissance) {
		var ret time.Time
		return ret
	}
	return *o.DateNaissance
}

// GetDateNaissanceOk returns a tuple with the DateNaissance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetDateNaissanceOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateNaissance) {
		return nil, false
	}
	return o.DateNaissance, true
}

// HasDateNaissance returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasDateNaissance() bool {
	if o != nil && !IsNil(o.DateNaissance) {
		return true
	}

	return false
}

// SetDateNaissance gets a reference to the given time.Time and assigns it to the DateNaissance field.
func (o *PartenaireToCashDtoV2) SetDateNaissance(v time.Time) {
	o.DateNaissance = &v
}

// GetLieuNaissance returns the LieuNaissance field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetLieuNaissance() string {
	if o == nil || IsNil(o.LieuNaissance) {
		var ret string
		return ret
	}
	return *o.LieuNaissance
}

// GetLieuNaissanceOk returns a tuple with the LieuNaissance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetLieuNaissanceOk() (*string, bool) {
	if o == nil || IsNil(o.LieuNaissance) {
		return nil, false
	}
	return o.LieuNaissance, true
}

// HasLieuNaissance returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasLieuNaissance() bool {
	if o != nil && !IsNil(o.LieuNaissance) {
		return true
	}

	return false
}

// SetLieuNaissance gets a reference to the given string and assigns it to the LieuNaissance field.
func (o *PartenaireToCashDtoV2) SetLieuNaissance(v string) {
	o.LieuNaissance = &v
}

// GetSituationMatrimoniale returns the SituationMatrimoniale field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetSituationMatrimoniale() string {
	if o == nil || IsNil(o.SituationMatrimoniale) {
		var ret string
		return ret
	}
	return *o.SituationMatrimoniale
}

// GetSituationMatrimonialeOk returns a tuple with the SituationMatrimoniale field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetSituationMatrimonialeOk() (*string, bool) {
	if o == nil || IsNil(o.SituationMatrimoniale) {
		return nil, false
	}
	return o.SituationMatrimoniale, true
}

// HasSituationMatrimoniale returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasSituationMatrimoniale() bool {
	if o != nil && !IsNil(o.SituationMatrimoniale) {
		return true
	}

	return false
}

// SetSituationMatrimoniale gets a reference to the given string and assigns it to the SituationMatrimoniale field.
func (o *PartenaireToCashDtoV2) SetSituationMatrimoniale(v string) {
	o.SituationMatrimoniale = &v
}

// GetGenre returns the Genre field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetGenre() string {
	if o == nil || IsNil(o.Genre) {
		var ret string
		return ret
	}
	return *o.Genre
}

// GetGenreOk returns a tuple with the Genre field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetGenreOk() (*string, bool) {
	if o == nil || IsNil(o.Genre) {
		return nil, false
	}
	return o.Genre, true
}

// HasGenre returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasGenre() bool {
	if o != nil && !IsNil(o.Genre) {
		return true
	}

	return false
}

// SetGenre gets a reference to the given string and assigns it to the Genre field.
func (o *PartenaireToCashDtoV2) SetGenre(v string) {
	o.Genre = &v
}

// GetProfession returns the Profession field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetProfession() string {
	if o == nil || IsNil(o.Profession) {
		var ret string
		return ret
	}
	return *o.Profession
}

// GetProfessionOk returns a tuple with the Profession field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetProfessionOk() (*string, bool) {
	if o == nil || IsNil(o.Profession) {
		return nil, false
	}
	return o.Profession, true
}

// HasProfession returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasProfession() bool {
	if o != nil && !IsNil(o.Profession) {
		return true
	}

	return false
}

// SetProfession gets a reference to the given string and assigns it to the Profession field.
func (o *PartenaireToCashDtoV2) SetProfession(v string) {
	o.Profession = &v
}

// GetAdresse returns the Adresse field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetAdresse() string {
	if o == nil || IsNil(o.Adresse) {
		var ret string
		return ret
	}
	return *o.Adresse
}

// GetAdresseOk returns a tuple with the Adresse field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetAdresseOk() (*string, bool) {
	if o == nil || IsNil(o.Adresse) {
		return nil, false
	}
	return o.Adresse, true
}

// HasAdresse returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasAdresse() bool {
	if o != nil && !IsNil(o.Adresse) {
		return true
	}

	return false
}

// SetAdresse gets a reference to the given string and assigns it to the Adresse field.
func (o *PartenaireToCashDtoV2) SetAdresse(v string) {
	o.Adresse = &v
}

// GetVilleResidence returns the VilleResidence field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetVilleResidence() string {
	if o == nil || IsNil(o.VilleResidence) {
		var ret string
		return ret
	}
	return *o.VilleResidence
}

// GetVilleResidenceOk returns a tuple with the VilleResidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetVilleResidenceOk() (*string, bool) {
	if o == nil || IsNil(o.VilleResidence) {
		return nil, false
	}
	return o.VilleResidence, true
}

// HasVilleResidence returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasVilleResidence() bool {
	if o != nil && !IsNil(o.VilleResidence) {
		return true
	}

	return false
}

// SetVilleResidence gets a reference to the given string and assigns it to the VilleResidence field.
func (o *PartenaireToCashDtoV2) SetVilleResidence(v string) {
	o.VilleResidence = &v
}

// GetPaysResidence returns the PaysResidence field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetPaysResidence() string {
	if o == nil || IsNil(o.PaysResidence) {
		var ret string
		return ret
	}
	return *o.PaysResidence
}

// GetPaysResidenceOk returns a tuple with the PaysResidence field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetPaysResidenceOk() (*string, bool) {
	if o == nil || IsNil(o.PaysResidence) {
		return nil, false
	}
	return o.PaysResidence, true
}

// HasPaysResidence returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasPaysResidence() bool {
	if o != nil && !IsNil(o.PaysResidence) {
		return true
	}

	return false
}

// SetPaysResidence gets a reference to the given string and assigns it to the PaysResidence field.
func (o *PartenaireToCashDtoV2) SetPaysResidence(v string) {
	o.PaysResidence = &v
}

// GetTypePiece returns the TypePiece field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetTypePiece() string {
	if o == nil || IsNil(o.TypePiece) {
		var ret string
		return ret
	}
	return *o.TypePiece
}

// GetTypePieceOk returns a tuple with the TypePiece field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetTypePieceOk() (*string, bool) {
	if o == nil || IsNil(o.TypePiece) {
		return nil, false
	}
	return o.TypePiece, true
}

// HasTypePiece returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasTypePiece() bool {
	if o != nil && !IsNil(o.TypePiece) {
		return true
	}

	return false
}

// SetTypePiece gets a reference to the given string and assigns it to the TypePiece field.
func (o *PartenaireToCashDtoV2) SetTypePiece(v string) {
	o.TypePiece = &v
}

// GetNumeroPiece returns the NumeroPiece field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetNumeroPiece() string {
	if o == nil || IsNil(o.NumeroPiece) {
		var ret string
		return ret
	}
	return *o.NumeroPiece
}

// GetNumeroPieceOk returns a tuple with the NumeroPiece field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetNumeroPieceOk() (*string, bool) {
	if o == nil || IsNil(o.NumeroPiece) {
		return nil, false
	}
	return o.NumeroPiece, true
}

// HasNumeroPiece returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasNumeroPiece() bool {
	if o != nil && !IsNil(o.NumeroPiece) {
		return true
	}

	return false
}

// SetNumeroPiece gets a reference to the given string and assigns it to the NumeroPiece field.
func (o *PartenaireToCashDtoV2) SetNumeroPiece(v string) {
	o.NumeroPiece = &v
}

// GetDateDelivrance returns the DateDelivrance field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetDateDelivrance() time.Time {
	if o == nil || IsNil(o.DateDelivrance) {
		var ret time.Time
		return ret
	}
	return *o.DateDelivrance
}

// GetDateDelivranceOk returns a tuple with the DateDelivrance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetDateDelivranceOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateDelivrance) {
		return nil, false
	}
	return o.DateDelivrance, true
}

// HasDateDelivrance returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasDateDelivrance() bool {
	if o != nil && !IsNil(o.DateDelivrance) {
		return true
	}

	return false
}

// SetDateDelivrance gets a reference to the given time.Time and assigns it to the DateDelivrance field.
func (o *PartenaireToCashDtoV2) SetDateDelivrance(v time.Time) {
	o.DateDelivrance = &v
}

// GetLieuDelivrance returns the LieuDelivrance field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetLieuDelivrance() string {
	if o == nil || IsNil(o.LieuDelivrance) {
		var ret string
		return ret
	}
	return *o.LieuDelivrance
}

// GetLieuDelivranceOk returns a tuple with the LieuDelivrance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetLieuDelivranceOk() (*string, bool) {
	if o == nil || IsNil(o.LieuDelivrance) {
		return nil, false
	}
	return o.LieuDelivrance, true
}

// HasLieuDelivrance returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasLieuDelivrance() bool {
	if o != nil && !IsNil(o.LieuDelivrance) {
		return true
	}

	return false
}

// SetLieuDelivrance gets a reference to the given string and assigns it to the LieuDelivrance field.
func (o *PartenaireToCashDtoV2) SetLieuDelivrance(v string) {
	o.LieuDelivrance = &v
}

// GetAutorite returns the Autorite field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetAutorite() string {
	if o == nil || IsNil(o.Autorite) {
		var ret string
		return ret
	}
	return *o.Autorite
}

// GetAutoriteOk returns a tuple with the Autorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetAutoriteOk() (*string, bool) {
	if o == nil || IsNil(o.Autorite) {
		return nil, false
	}
	return o.Autorite, true
}

// HasAutorite returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasAutorite() bool {
	if o != nil && !IsNil(o.Autorite) {
		return true
	}

	return false
}

// SetAutorite gets a reference to the given string and assigns it to the Autorite field.
func (o *PartenaireToCashDtoV2) SetAutorite(v string) {
	o.Autorite = &v
}

// GetPhotoPieceIdentiteRecto returns the PhotoPieceIdentiteRecto field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetPhotoPieceIdentiteRecto() string {
	if o == nil || IsNil(o.PhotoPieceIdentiteRecto) {
		var ret string
		return ret
	}
	return *o.PhotoPieceIdentiteRecto
}

// GetPhotoPieceIdentiteRectoOk returns a tuple with the PhotoPieceIdentiteRecto field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetPhotoPieceIdentiteRectoOk() (*string, bool) {
	if o == nil || IsNil(o.PhotoPieceIdentiteRecto) {
		return nil, false
	}
	return o.PhotoPieceIdentiteRecto, true
}

// HasPhotoPieceIdentiteRecto returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasPhotoPieceIdentiteRecto() bool {
	if o != nil && !IsNil(o.PhotoPieceIdentiteRecto) {
		return true
	}

	return false
}

// SetPhotoPieceIdentiteRecto gets a reference to the given string and assigns it to the PhotoPieceIdentiteRecto field.
func (o *PartenaireToCashDtoV2) SetPhotoPieceIdentiteRecto(v string) {
	o.PhotoPieceIdentiteRecto = &v
}

// GetPhotoPieceIdentiteVerso returns the PhotoPieceIdentiteVerso field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetPhotoPieceIdentiteVerso() string {
	if o == nil || IsNil(o.PhotoPieceIdentiteVerso) {
		var ret string
		return ret
	}
	return *o.PhotoPieceIdentiteVerso
}

// GetPhotoPieceIdentiteVersoOk returns a tuple with the PhotoPieceIdentiteVerso field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetPhotoPieceIdentiteVersoOk() (*string, bool) {
	if o == nil || IsNil(o.PhotoPieceIdentiteVerso) {
		return nil, false
	}
	return o.PhotoPieceIdentiteVerso, true
}

// HasPhotoPieceIdentiteVerso returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasPhotoPieceIdentiteVerso() bool {
	if o != nil && !IsNil(o.PhotoPieceIdentiteVerso) {
		return true
	}

	return false
}

// SetPhotoPieceIdentiteVerso gets a reference to the given string and assigns it to the PhotoPieceIdentiteVerso field.
func (o *PartenaireToCashDtoV2) SetPhotoPieceIdentiteVerso(v string) {
	o.PhotoPieceIdentiteVerso = &v
}

// GetPhotoIdentite returns the PhotoIdentite field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetPhotoIdentite() string {
	if o == nil || IsNil(o.PhotoIdentite) {
		var ret string
		return ret
	}
	return *o.PhotoIdentite
}

// GetPhotoIdentiteOk returns a tuple with the PhotoIdentite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetPhotoIdentiteOk() (*string, bool) {
	if o == nil || IsNil(o.PhotoIdentite) {
		return nil, false
	}
	return o.PhotoIdentite, true
}

// HasPhotoIdentite returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasPhotoIdentite() bool {
	if o != nil && !IsNil(o.PhotoIdentite) {
		return true
	}

	return false
}

// SetPhotoIdentite gets a reference to the given string and assigns it to the PhotoIdentite field.
func (o *PartenaireToCashDtoV2) SetPhotoIdentite(v string) {
	o.PhotoIdentite = &v
}

// GetRequestId returns the RequestId field value
func (o *PartenaireToCashDtoV2) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *PartenaireToCashDtoV2) SetRequestId(v string) {
	o.RequestId = v
}

// GetFraisInclus returns the FraisInclus field value
func (o *PartenaireToCashDtoV2) GetFraisInclus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FraisInclus
}

// GetFraisInclusOk returns a tuple with the FraisInclus field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetFraisInclusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FraisInclus, true
}

// SetFraisInclus sets field value
func (o *PartenaireToCashDtoV2) SetFraisInclus(v bool) {
	o.FraisInclus = v
}

// GetMontant returns the Montant field value
func (o *PartenaireToCashDtoV2) GetMontant() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Montant
}

// GetMontantOk returns a tuple with the Montant field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetMontantOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Montant, true
}

// SetMontant sets field value
func (o *PartenaireToCashDtoV2) SetMontant(v float64) {
	o.Montant = v
}

// GetVilleDestination returns the VilleDestination field value
func (o *PartenaireToCashDtoV2) GetVilleDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VilleDestination
}

// GetVilleDestinationOk returns a tuple with the VilleDestination field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetVilleDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VilleDestination, true
}

// SetVilleDestination sets field value
func (o *PartenaireToCashDtoV2) SetVilleDestination(v string) {
	o.VilleDestination = v
}

// GetNomDestinataire returns the NomDestinataire field value
func (o *PartenaireToCashDtoV2) GetNomDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NomDestinataire
}

// GetNomDestinataireOk returns a tuple with the NomDestinataire field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetNomDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NomDestinataire, true
}

// SetNomDestinataire sets field value
func (o *PartenaireToCashDtoV2) SetNomDestinataire(v string) {
	o.NomDestinataire = v
}

// GetPrenomDestinataire returns the PrenomDestinataire field value
func (o *PartenaireToCashDtoV2) GetPrenomDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrenomDestinataire
}

// GetPrenomDestinataireOk returns a tuple with the PrenomDestinataire field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetPrenomDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrenomDestinataire, true
}

// SetPrenomDestinataire sets field value
func (o *PartenaireToCashDtoV2) SetPrenomDestinataire(v string) {
	o.PrenomDestinataire = v
}

// GetIndicatifDestinataire returns the IndicatifDestinataire field value
func (o *PartenaireToCashDtoV2) GetIndicatifDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndicatifDestinataire
}

// GetIndicatifDestinataireOk returns a tuple with the IndicatifDestinataire field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetIndicatifDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndicatifDestinataire, true
}

// SetIndicatifDestinataire sets field value
func (o *PartenaireToCashDtoV2) SetIndicatifDestinataire(v string) {
	o.IndicatifDestinataire = v
}

// GetNumeroDestinataire returns the NumeroDestinataire field value
func (o *PartenaireToCashDtoV2) GetNumeroDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NumeroDestinataire
}

// GetNumeroDestinataireOk returns a tuple with the NumeroDestinataire field value
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetNumeroDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumeroDestinataire, true
}

// SetNumeroDestinataire sets field value
func (o *PartenaireToCashDtoV2) SetNumeroDestinataire(v string) {
	o.NumeroDestinataire = v
}

// GetMotifTransaction returns the MotifTransaction field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetMotifTransaction() string {
	if o == nil || IsNil(o.MotifTransaction) {
		var ret string
		return ret
	}
	return *o.MotifTransaction
}

// GetMotifTransactionOk returns a tuple with the MotifTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetMotifTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.MotifTransaction) {
		return nil, false
	}
	return o.MotifTransaction, true
}

// HasMotifTransaction returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasMotifTransaction() bool {
	if o != nil && !IsNil(o.MotifTransaction) {
		return true
	}

	return false
}

// SetMotifTransaction gets a reference to the given string and assigns it to the MotifTransaction field.
func (o *PartenaireToCashDtoV2) SetMotifTransaction(v string) {
	o.MotifTransaction = &v
}

// GetAdresseIp returns the AdresseIp field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetAdresseIp() string {
	if o == nil || IsNil(o.AdresseIp) {
		var ret string
		return ret
	}
	return *o.AdresseIp
}

// GetAdresseIpOk returns a tuple with the AdresseIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetAdresseIpOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIp) {
		return nil, false
	}
	return o.AdresseIp, true
}

// HasAdresseIp returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasAdresseIp() bool {
	if o != nil && !IsNil(o.AdresseIp) {
		return true
	}

	return false
}

// SetAdresseIp gets a reference to the given string and assigns it to the AdresseIp field.
func (o *PartenaireToCashDtoV2) SetAdresseIp(v string) {
	o.AdresseIp = &v
}

// GetUrlCallback returns the UrlCallback field value if set, zero value otherwise.
func (o *PartenaireToCashDtoV2) GetUrlCallback() string {
	if o == nil || IsNil(o.UrlCallback) {
		var ret string
		return ret
	}
	return *o.UrlCallback
}

// GetUrlCallbackOk returns a tuple with the UrlCallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToCashDtoV2) GetUrlCallbackOk() (*string, bool) {
	if o == nil || IsNil(o.UrlCallback) {
		return nil, false
	}
	return o.UrlCallback, true
}

// HasUrlCallback returns a boolean if a field has been set.
func (o *PartenaireToCashDtoV2) HasUrlCallback() bool {
	if o != nil && !IsNil(o.UrlCallback) {
		return true
	}

	return false
}

// SetUrlCallback gets a reference to the given string and assigns it to the UrlCallback field.
func (o *PartenaireToCashDtoV2) SetUrlCallback(v string) {
	o.UrlCallback = &v
}

func (o PartenaireToCashDtoV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartenaireToCashDtoV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["nom"] = o.Nom
	toSerialize["prenom"] = o.Prenom
	toSerialize["indicatif"] = o.Indicatif
	toSerialize["numero"] = o.Numero
	if !IsNil(o.DateNaissance) {
		toSerialize["dateNaissance"] = o.DateNaissance
	}
	if !IsNil(o.LieuNaissance) {
		toSerialize["lieuNaissance"] = o.LieuNaissance
	}
	if !IsNil(o.SituationMatrimoniale) {
		toSerialize["situationMatrimoniale"] = o.SituationMatrimoniale
	}
	if !IsNil(o.Genre) {
		toSerialize["genre"] = o.Genre
	}
	if !IsNil(o.Profession) {
		toSerialize["profession"] = o.Profession
	}
	if !IsNil(o.Adresse) {
		toSerialize["adresse"] = o.Adresse
	}
	if !IsNil(o.VilleResidence) {
		toSerialize["villeResidence"] = o.VilleResidence
	}
	if !IsNil(o.PaysResidence) {
		toSerialize["paysResidence"] = o.PaysResidence
	}
	if !IsNil(o.TypePiece) {
		toSerialize["typePiece"] = o.TypePiece
	}
	if !IsNil(o.NumeroPiece) {
		toSerialize["numeroPiece"] = o.NumeroPiece
	}
	if !IsNil(o.DateDelivrance) {
		toSerialize["dateDelivrance"] = o.DateDelivrance
	}
	if !IsNil(o.LieuDelivrance) {
		toSerialize["lieuDelivrance"] = o.LieuDelivrance
	}
	if !IsNil(o.Autorite) {
		toSerialize["autorite"] = o.Autorite
	}
	if !IsNil(o.PhotoPieceIdentiteRecto) {
		toSerialize["photoPieceIdentiteRecto"] = o.PhotoPieceIdentiteRecto
	}
	if !IsNil(o.PhotoPieceIdentiteVerso) {
		toSerialize["photoPieceIdentiteVerso"] = o.PhotoPieceIdentiteVerso
	}
	if !IsNil(o.PhotoIdentite) {
		toSerialize["photoIdentite"] = o.PhotoIdentite
	}
	toSerialize["requestId"] = o.RequestId
	toSerialize["fraisInclus"] = o.FraisInclus
	toSerialize["montant"] = o.Montant
	toSerialize["villeDestination"] = o.VilleDestination
	toSerialize["nomDestinataire"] = o.NomDestinataire
	toSerialize["prenomDestinataire"] = o.PrenomDestinataire
	toSerialize["indicatifDestinataire"] = o.IndicatifDestinataire
	toSerialize["numeroDestinataire"] = o.NumeroDestinataire
	if !IsNil(o.MotifTransaction) {
		toSerialize["motifTransaction"] = o.MotifTransaction
	}
	if !IsNil(o.AdresseIp) {
		toSerialize["adresseIp"] = o.AdresseIp
	}
	if !IsNil(o.UrlCallback) {
		toSerialize["urlCallback"] = o.UrlCallback
	}
	return toSerialize, nil
}

func (o *PartenaireToCashDtoV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"nom",
		"prenom",
		"indicatif",
		"numero",
		"requestId",
		"fraisInclus",
		"montant",
		"villeDestination",
		"nomDestinataire",
		"prenomDestinataire",
		"indicatifDestinataire",
		"numeroDestinataire",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPartenaireToCashDtoV2 := _PartenaireToCashDtoV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPartenaireToCashDtoV2)

	if err != nil {
		return err
	}

	*o = PartenaireToCashDtoV2(varPartenaireToCashDtoV2)

	return err
}

type NullablePartenaireToCashDtoV2 struct {
	value *PartenaireToCashDtoV2
	isSet bool
}

func (v NullablePartenaireToCashDtoV2) Get() *PartenaireToCashDtoV2 {
	return v.value
}

func (v *NullablePartenaireToCashDtoV2) Set(val *PartenaireToCashDtoV2) {
	v.value = val
	v.isSet = true
}

func (v NullablePartenaireToCashDtoV2) IsSet() bool {
	return v.isSet
}

func (v *NullablePartenaireToCashDtoV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartenaireToCashDtoV2(val *PartenaireToCashDtoV2) *NullablePartenaireToCashDtoV2 {
	return &NullablePartenaireToCashDtoV2{value: val, isSet: true}
}

func (v NullablePartenaireToCashDtoV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartenaireToCashDtoV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


