/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the CheckAchatStatusModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckAchatStatusModel{}

// CheckAchatStatusModel struct for CheckAchatStatusModel
type CheckAchatStatusModel struct {
	RequestId *string `json:"requestId,omitempty"`
	LongTransaction *string `json:"longTransaction,omitempty"`
	LatTransaction *string `json:"latTransaction,omitempty"`
	AdresseIp *string `json:"adresseIp,omitempty"`
}

// NewCheckAchatStatusModel instantiates a new CheckAchatStatusModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckAchatStatusModel() *CheckAchatStatusModel {
	this := CheckAchatStatusModel{}
	return &this
}

// NewCheckAchatStatusModelWithDefaults instantiates a new CheckAchatStatusModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckAchatStatusModelWithDefaults() *CheckAchatStatusModel {
	this := CheckAchatStatusModel{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CheckAchatStatusModel) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusModel) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CheckAchatStatusModel) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CheckAchatStatusModel) SetRequestId(v string) {
	o.RequestId = &v
}

// GetLongTransaction returns the LongTransaction field value if set, zero value otherwise.
func (o *CheckAchatStatusModel) GetLongTransaction() string {
	if o == nil || IsNil(o.LongTransaction) {
		var ret string
		return ret
	}
	return *o.LongTransaction
}

// GetLongTransactionOk returns a tuple with the LongTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusModel) GetLongTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.LongTransaction) {
		return nil, false
	}
	return o.LongTransaction, true
}

// HasLongTransaction returns a boolean if a field has been set.
func (o *CheckAchatStatusModel) HasLongTransaction() bool {
	if o != nil && !IsNil(o.LongTransaction) {
		return true
	}

	return false
}

// SetLongTransaction gets a reference to the given string and assigns it to the LongTransaction field.
func (o *CheckAchatStatusModel) SetLongTransaction(v string) {
	o.LongTransaction = &v
}

// GetLatTransaction returns the LatTransaction field value if set, zero value otherwise.
func (o *CheckAchatStatusModel) GetLatTransaction() string {
	if o == nil || IsNil(o.LatTransaction) {
		var ret string
		return ret
	}
	return *o.LatTransaction
}

// GetLatTransactionOk returns a tuple with the LatTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusModel) GetLatTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.LatTransaction) {
		return nil, false
	}
	return o.LatTransaction, true
}

// HasLatTransaction returns a boolean if a field has been set.
func (o *CheckAchatStatusModel) HasLatTransaction() bool {
	if o != nil && !IsNil(o.LatTransaction) {
		return true
	}

	return false
}

// SetLatTransaction gets a reference to the given string and assigns it to the LatTransaction field.
func (o *CheckAchatStatusModel) SetLatTransaction(v string) {
	o.LatTransaction = &v
}

// GetAdresseIp returns the AdresseIp field value if set, zero value otherwise.
func (o *CheckAchatStatusModel) GetAdresseIp() string {
	if o == nil || IsNil(o.AdresseIp) {
		var ret string
		return ret
	}
	return *o.AdresseIp
}

// GetAdresseIpOk returns a tuple with the AdresseIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusModel) GetAdresseIpOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIp) {
		return nil, false
	}
	return o.AdresseIp, true
}

// HasAdresseIp returns a boolean if a field has been set.
func (o *CheckAchatStatusModel) HasAdresseIp() bool {
	if o != nil && !IsNil(o.AdresseIp) {
		return true
	}

	return false
}

// SetAdresseIp gets a reference to the given string and assigns it to the AdresseIp field.
func (o *CheckAchatStatusModel) SetAdresseIp(v string) {
	o.AdresseIp = &v
}

func (o CheckAchatStatusModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckAchatStatusModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.LongTransaction) {
		toSerialize["longTransaction"] = o.LongTransaction
	}
	if !IsNil(o.LatTransaction) {
		toSerialize["latTransaction"] = o.LatTransaction
	}
	if !IsNil(o.AdresseIp) {
		toSerialize["adresseIp"] = o.AdresseIp
	}
	return toSerialize, nil
}

type NullableCheckAchatStatusModel struct {
	value *CheckAchatStatusModel
	isSet bool
}

func (v NullableCheckAchatStatusModel) Get() *CheckAchatStatusModel {
	return v.value
}

func (v *NullableCheckAchatStatusModel) Set(val *CheckAchatStatusModel) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckAchatStatusModel) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckAchatStatusModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckAchatStatusModel(val *CheckAchatStatusModel) *NullableCheckAchatStatusModel {
	return &NullableCheckAchatStatusModel{value: val, isSet: true}
}

func (v NullableCheckAchatStatusModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckAchatStatusModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


