/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"time"
)

// checks if the PartenaireToWalletResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PartenaireToWalletResponseV2{}

// PartenaireToWalletResponseV2 struct for PartenaireToWalletResponseV2
type PartenaireToWalletResponseV2 struct {
	PublicId *string `json:"publicId,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	AdresseIP *string `json:"adresseIP,omitempty"`
	Reference *string `json:"reference,omitempty"`
	Motif *string `json:"motif,omitempty"`
	MontantRecharge *float64 `json:"montantRecharge,omitempty"`
	FraisRecharge *float64 `json:"fraisRecharge,omitempty"`
	MontantTotalTransaction *float64 `json:"montantTotalTransaction,omitempty"`
	StatusTransaction *string `json:"statusTransaction,omitempty"`
	TypeTransaction *string `json:"typeTransaction,omitempty"`
	CompteClient *string `json:"compteClient,omitempty"`
	NomDeposant *string `json:"nomDeposant,omitempty"`
	PrenomDeposant *string `json:"prenomDeposant,omitempty"`
	PhoneDeposant *string `json:"phoneDeposant,omitempty"`
	TypePieceDeposant *string `json:"typePieceDeposant,omitempty"`
	NumeroPieceDeposant *string `json:"numeroPieceDeposant,omitempty"`
	ComptePartenaire *string `json:"ComptePartenaire,omitempty"`
	NomPartenaire *string `json:"nomPartenaire,omitempty"`
	PrenomPartenaire *string `json:"prenomPartenaire,omitempty"`
	DateTransaction *time.Time `json:"dateTransaction,omitempty"`
}

// NewPartenaireToWalletResponseV2 instantiates a new PartenaireToWalletResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPartenaireToWalletResponseV2() *PartenaireToWalletResponseV2 {
	this := PartenaireToWalletResponseV2{}
	return &this
}

// NewPartenaireToWalletResponseV2WithDefaults instantiates a new PartenaireToWalletResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPartenaireToWalletResponseV2WithDefaults() *PartenaireToWalletResponseV2 {
	this := PartenaireToWalletResponseV2{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetPublicId() string {
	if o == nil || IsNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetPublicIdOk() (*string, bool) {
	if o == nil || IsNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasPublicId() bool {
	if o != nil && !IsNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *PartenaireToWalletResponseV2) SetPublicId(v string) {
	o.PublicId = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *PartenaireToWalletResponseV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetAdresseIP returns the AdresseIP field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetAdresseIP() string {
	if o == nil || IsNil(o.AdresseIP) {
		var ret string
		return ret
	}
	return *o.AdresseIP
}

// GetAdresseIPOk returns a tuple with the AdresseIP field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetAdresseIPOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIP) {
		return nil, false
	}
	return o.AdresseIP, true
}

// HasAdresseIP returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasAdresseIP() bool {
	if o != nil && !IsNil(o.AdresseIP) {
		return true
	}

	return false
}

// SetAdresseIP gets a reference to the given string and assigns it to the AdresseIP field.
func (o *PartenaireToWalletResponseV2) SetAdresseIP(v string) {
	o.AdresseIP = &v
}

// GetReference returns the Reference field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetReference() string {
	if o == nil || IsNil(o.Reference) {
		var ret string
		return ret
	}
	return *o.Reference
}

// GetReferenceOk returns a tuple with the Reference field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetReferenceOk() (*string, bool) {
	if o == nil || IsNil(o.Reference) {
		return nil, false
	}
	return o.Reference, true
}

// HasReference returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasReference() bool {
	if o != nil && !IsNil(o.Reference) {
		return true
	}

	return false
}

// SetReference gets a reference to the given string and assigns it to the Reference field.
func (o *PartenaireToWalletResponseV2) SetReference(v string) {
	o.Reference = &v
}

// GetMotif returns the Motif field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetMotif() string {
	if o == nil || IsNil(o.Motif) {
		var ret string
		return ret
	}
	return *o.Motif
}

// GetMotifOk returns a tuple with the Motif field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetMotifOk() (*string, bool) {
	if o == nil || IsNil(o.Motif) {
		return nil, false
	}
	return o.Motif, true
}

// HasMotif returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasMotif() bool {
	if o != nil && !IsNil(o.Motif) {
		return true
	}

	return false
}

// SetMotif gets a reference to the given string and assigns it to the Motif field.
func (o *PartenaireToWalletResponseV2) SetMotif(v string) {
	o.Motif = &v
}

// GetMontantRecharge returns the MontantRecharge field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetMontantRecharge() float64 {
	if o == nil || IsNil(o.MontantRecharge) {
		var ret float64
		return ret
	}
	return *o.MontantRecharge
}

// GetMontantRechargeOk returns a tuple with the MontantRecharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetMontantRechargeOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantRecharge) {
		return nil, false
	}
	return o.MontantRecharge, true
}

// HasMontantRecharge returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasMontantRecharge() bool {
	if o != nil && !IsNil(o.MontantRecharge) {
		return true
	}

	return false
}

// SetMontantRecharge gets a reference to the given float64 and assigns it to the MontantRecharge field.
func (o *PartenaireToWalletResponseV2) SetMontantRecharge(v float64) {
	o.MontantRecharge = &v
}

// GetFraisRecharge returns the FraisRecharge field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetFraisRecharge() float64 {
	if o == nil || IsNil(o.FraisRecharge) {
		var ret float64
		return ret
	}
	return *o.FraisRecharge
}

// GetFraisRechargeOk returns a tuple with the FraisRecharge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetFraisRechargeOk() (*float64, bool) {
	if o == nil || IsNil(o.FraisRecharge) {
		return nil, false
	}
	return o.FraisRecharge, true
}

// HasFraisRecharge returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasFraisRecharge() bool {
	if o != nil && !IsNil(o.FraisRecharge) {
		return true
	}

	return false
}

// SetFraisRecharge gets a reference to the given float64 and assigns it to the FraisRecharge field.
func (o *PartenaireToWalletResponseV2) SetFraisRecharge(v float64) {
	o.FraisRecharge = &v
}

// GetMontantTotalTransaction returns the MontantTotalTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetMontantTotalTransaction() float64 {
	if o == nil || IsNil(o.MontantTotalTransaction) {
		var ret float64
		return ret
	}
	return *o.MontantTotalTransaction
}

// GetMontantTotalTransactionOk returns a tuple with the MontantTotalTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetMontantTotalTransactionOk() (*float64, bool) {
	if o == nil || IsNil(o.MontantTotalTransaction) {
		return nil, false
	}
	return o.MontantTotalTransaction, true
}

// HasMontantTotalTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasMontantTotalTransaction() bool {
	if o != nil && !IsNil(o.MontantTotalTransaction) {
		return true
	}

	return false
}

// SetMontantTotalTransaction gets a reference to the given float64 and assigns it to the MontantTotalTransaction field.
func (o *PartenaireToWalletResponseV2) SetMontantTotalTransaction(v float64) {
	o.MontantTotalTransaction = &v
}

// GetStatusTransaction returns the StatusTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetStatusTransaction() string {
	if o == nil || IsNil(o.StatusTransaction) {
		var ret string
		return ret
	}
	return *o.StatusTransaction
}

// GetStatusTransactionOk returns a tuple with the StatusTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetStatusTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.StatusTransaction) {
		return nil, false
	}
	return o.StatusTransaction, true
}

// HasStatusTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasStatusTransaction() bool {
	if o != nil && !IsNil(o.StatusTransaction) {
		return true
	}

	return false
}

// SetStatusTransaction gets a reference to the given string and assigns it to the StatusTransaction field.
func (o *PartenaireToWalletResponseV2) SetStatusTransaction(v string) {
	o.StatusTransaction = &v
}

// GetTypeTransaction returns the TypeTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetTypeTransaction() string {
	if o == nil || IsNil(o.TypeTransaction) {
		var ret string
		return ret
	}
	return *o.TypeTransaction
}

// GetTypeTransactionOk returns a tuple with the TypeTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetTypeTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeTransaction) {
		return nil, false
	}
	return o.TypeTransaction, true
}

// HasTypeTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasTypeTransaction() bool {
	if o != nil && !IsNil(o.TypeTransaction) {
		return true
	}

	return false
}

// SetTypeTransaction gets a reference to the given string and assigns it to the TypeTransaction field.
func (o *PartenaireToWalletResponseV2) SetTypeTransaction(v string) {
	o.TypeTransaction = &v
}

// GetCompteClient returns the CompteClient field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetCompteClient() string {
	if o == nil || IsNil(o.CompteClient) {
		var ret string
		return ret
	}
	return *o.CompteClient
}

// GetCompteClientOk returns a tuple with the CompteClient field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetCompteClientOk() (*string, bool) {
	if o == nil || IsNil(o.CompteClient) {
		return nil, false
	}
	return o.CompteClient, true
}

// HasCompteClient returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasCompteClient() bool {
	if o != nil && !IsNil(o.CompteClient) {
		return true
	}

	return false
}

// SetCompteClient gets a reference to the given string and assigns it to the CompteClient field.
func (o *PartenaireToWalletResponseV2) SetCompteClient(v string) {
	o.CompteClient = &v
}

// GetNomDeposant returns the NomDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetNomDeposant() string {
	if o == nil || IsNil(o.NomDeposant) {
		var ret string
		return ret
	}
	return *o.NomDeposant
}

// GetNomDeposantOk returns a tuple with the NomDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetNomDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.NomDeposant) {
		return nil, false
	}
	return o.NomDeposant, true
}

// HasNomDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasNomDeposant() bool {
	if o != nil && !IsNil(o.NomDeposant) {
		return true
	}

	return false
}

// SetNomDeposant gets a reference to the given string and assigns it to the NomDeposant field.
func (o *PartenaireToWalletResponseV2) SetNomDeposant(v string) {
	o.NomDeposant = &v
}

// GetPrenomDeposant returns the PrenomDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetPrenomDeposant() string {
	if o == nil || IsNil(o.PrenomDeposant) {
		var ret string
		return ret
	}
	return *o.PrenomDeposant
}

// GetPrenomDeposantOk returns a tuple with the PrenomDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetPrenomDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomDeposant) {
		return nil, false
	}
	return o.PrenomDeposant, true
}

// HasPrenomDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasPrenomDeposant() bool {
	if o != nil && !IsNil(o.PrenomDeposant) {
		return true
	}

	return false
}

// SetPrenomDeposant gets a reference to the given string and assigns it to the PrenomDeposant field.
func (o *PartenaireToWalletResponseV2) SetPrenomDeposant(v string) {
	o.PrenomDeposant = &v
}

// GetPhoneDeposant returns the PhoneDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetPhoneDeposant() string {
	if o == nil || IsNil(o.PhoneDeposant) {
		var ret string
		return ret
	}
	return *o.PhoneDeposant
}

// GetPhoneDeposantOk returns a tuple with the PhoneDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetPhoneDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.PhoneDeposant) {
		return nil, false
	}
	return o.PhoneDeposant, true
}

// HasPhoneDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasPhoneDeposant() bool {
	if o != nil && !IsNil(o.PhoneDeposant) {
		return true
	}

	return false
}

// SetPhoneDeposant gets a reference to the given string and assigns it to the PhoneDeposant field.
func (o *PartenaireToWalletResponseV2) SetPhoneDeposant(v string) {
	o.PhoneDeposant = &v
}

// GetTypePieceDeposant returns the TypePieceDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetTypePieceDeposant() string {
	if o == nil || IsNil(o.TypePieceDeposant) {
		var ret string
		return ret
	}
	return *o.TypePieceDeposant
}

// GetTypePieceDeposantOk returns a tuple with the TypePieceDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetTypePieceDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.TypePieceDeposant) {
		return nil, false
	}
	return o.TypePieceDeposant, true
}

// HasTypePieceDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasTypePieceDeposant() bool {
	if o != nil && !IsNil(o.TypePieceDeposant) {
		return true
	}

	return false
}

// SetTypePieceDeposant gets a reference to the given string and assigns it to the TypePieceDeposant field.
func (o *PartenaireToWalletResponseV2) SetTypePieceDeposant(v string) {
	o.TypePieceDeposant = &v
}

// GetNumeroPieceDeposant returns the NumeroPieceDeposant field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetNumeroPieceDeposant() string {
	if o == nil || IsNil(o.NumeroPieceDeposant) {
		var ret string
		return ret
	}
	return *o.NumeroPieceDeposant
}

// GetNumeroPieceDeposantOk returns a tuple with the NumeroPieceDeposant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetNumeroPieceDeposantOk() (*string, bool) {
	if o == nil || IsNil(o.NumeroPieceDeposant) {
		return nil, false
	}
	return o.NumeroPieceDeposant, true
}

// HasNumeroPieceDeposant returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasNumeroPieceDeposant() bool {
	if o != nil && !IsNil(o.NumeroPieceDeposant) {
		return true
	}

	return false
}

// SetNumeroPieceDeposant gets a reference to the given string and assigns it to the NumeroPieceDeposant field.
func (o *PartenaireToWalletResponseV2) SetNumeroPieceDeposant(v string) {
	o.NumeroPieceDeposant = &v
}

// GetComptePartenaire returns the ComptePartenaire field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetComptePartenaire() string {
	if o == nil || IsNil(o.ComptePartenaire) {
		var ret string
		return ret
	}
	return *o.ComptePartenaire
}

// GetComptePartenaireOk returns a tuple with the ComptePartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetComptePartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.ComptePartenaire) {
		return nil, false
	}
	return o.ComptePartenaire, true
}

// HasComptePartenaire returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasComptePartenaire() bool {
	if o != nil && !IsNil(o.ComptePartenaire) {
		return true
	}

	return false
}

// SetComptePartenaire gets a reference to the given string and assigns it to the ComptePartenaire field.
func (o *PartenaireToWalletResponseV2) SetComptePartenaire(v string) {
	o.ComptePartenaire = &v
}

// GetNomPartenaire returns the NomPartenaire field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetNomPartenaire() string {
	if o == nil || IsNil(o.NomPartenaire) {
		var ret string
		return ret
	}
	return *o.NomPartenaire
}

// GetNomPartenaireOk returns a tuple with the NomPartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetNomPartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.NomPartenaire) {
		return nil, false
	}
	return o.NomPartenaire, true
}

// HasNomPartenaire returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasNomPartenaire() bool {
	if o != nil && !IsNil(o.NomPartenaire) {
		return true
	}

	return false
}

// SetNomPartenaire gets a reference to the given string and assigns it to the NomPartenaire field.
func (o *PartenaireToWalletResponseV2) SetNomPartenaire(v string) {
	o.NomPartenaire = &v
}

// GetPrenomPartenaire returns the PrenomPartenaire field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetPrenomPartenaire() string {
	if o == nil || IsNil(o.PrenomPartenaire) {
		var ret string
		return ret
	}
	return *o.PrenomPartenaire
}

// GetPrenomPartenaireOk returns a tuple with the PrenomPartenaire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetPrenomPartenaireOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomPartenaire) {
		return nil, false
	}
	return o.PrenomPartenaire, true
}

// HasPrenomPartenaire returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasPrenomPartenaire() bool {
	if o != nil && !IsNil(o.PrenomPartenaire) {
		return true
	}

	return false
}

// SetPrenomPartenaire gets a reference to the given string and assigns it to the PrenomPartenaire field.
func (o *PartenaireToWalletResponseV2) SetPrenomPartenaire(v string) {
	o.PrenomPartenaire = &v
}

// GetDateTransaction returns the DateTransaction field value if set, zero value otherwise.
func (o *PartenaireToWalletResponseV2) GetDateTransaction() time.Time {
	if o == nil || IsNil(o.DateTransaction) {
		var ret time.Time
		return ret
	}
	return *o.DateTransaction
}

// GetDateTransactionOk returns a tuple with the DateTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PartenaireToWalletResponseV2) GetDateTransactionOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateTransaction) {
		return nil, false
	}
	return o.DateTransaction, true
}

// HasDateTransaction returns a boolean if a field has been set.
func (o *PartenaireToWalletResponseV2) HasDateTransaction() bool {
	if o != nil && !IsNil(o.DateTransaction) {
		return true
	}

	return false
}

// SetDateTransaction gets a reference to the given time.Time and assigns it to the DateTransaction field.
func (o *PartenaireToWalletResponseV2) SetDateTransaction(v time.Time) {
	o.DateTransaction = &v
}

func (o PartenaireToWalletResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PartenaireToWalletResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.AdresseIP) {
		toSerialize["adresseIP"] = o.AdresseIP
	}
	if !IsNil(o.Reference) {
		toSerialize["reference"] = o.Reference
	}
	if !IsNil(o.Motif) {
		toSerialize["motif"] = o.Motif
	}
	if !IsNil(o.MontantRecharge) {
		toSerialize["montantRecharge"] = o.MontantRecharge
	}
	if !IsNil(o.FraisRecharge) {
		toSerialize["fraisRecharge"] = o.FraisRecharge
	}
	if !IsNil(o.MontantTotalTransaction) {
		toSerialize["montantTotalTransaction"] = o.MontantTotalTransaction
	}
	if !IsNil(o.StatusTransaction) {
		toSerialize["statusTransaction"] = o.StatusTransaction
	}
	if !IsNil(o.TypeTransaction) {
		toSerialize["typeTransaction"] = o.TypeTransaction
	}
	if !IsNil(o.CompteClient) {
		toSerialize["compteClient"] = o.CompteClient
	}
	if !IsNil(o.NomDeposant) {
		toSerialize["nomDeposant"] = o.NomDeposant
	}
	if !IsNil(o.PrenomDeposant) {
		toSerialize["prenomDeposant"] = o.PrenomDeposant
	}
	if !IsNil(o.PhoneDeposant) {
		toSerialize["phoneDeposant"] = o.PhoneDeposant
	}
	if !IsNil(o.TypePieceDeposant) {
		toSerialize["typePieceDeposant"] = o.TypePieceDeposant
	}
	if !IsNil(o.NumeroPieceDeposant) {
		toSerialize["numeroPieceDeposant"] = o.NumeroPieceDeposant
	}
	if !IsNil(o.ComptePartenaire) {
		toSerialize["ComptePartenaire"] = o.ComptePartenaire
	}
	if !IsNil(o.NomPartenaire) {
		toSerialize["nomPartenaire"] = o.NomPartenaire
	}
	if !IsNil(o.PrenomPartenaire) {
		toSerialize["prenomPartenaire"] = o.PrenomPartenaire
	}
	if !IsNil(o.DateTransaction) {
		toSerialize["dateTransaction"] = o.DateTransaction
	}
	return toSerialize, nil
}

type NullablePartenaireToWalletResponseV2 struct {
	value *PartenaireToWalletResponseV2
	isSet bool
}

func (v NullablePartenaireToWalletResponseV2) Get() *PartenaireToWalletResponseV2 {
	return v.value
}

func (v *NullablePartenaireToWalletResponseV2) Set(val *PartenaireToWalletResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullablePartenaireToWalletResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullablePartenaireToWalletResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePartenaireToWalletResponseV2(val *PartenaireToWalletResponseV2) *NullablePartenaireToWalletResponseV2 {
	return &NullablePartenaireToWalletResponseV2{value: val, isSet: true}
}

func (v NullablePartenaireToWalletResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePartenaireToWalletResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


