/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AchatEnLigneModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AchatEnLigneModel{}

// AchatEnLigneModel struct for AchatEnLigneModel
type AchatEnLigneModel struct {
	DescriptionAchat []string `json:"descriptionAchat"`
	MontantTransaction float64 `json:"montantTransaction"`
	PhoneClient string `json:"phoneClient"`
	MotifTransaction string `json:"motifTransaction"`
	LongTransaction *string `json:"longTransaction,omitempty"`
	LatTransaction *string `json:"latTransaction,omitempty"`
	RequestId string `json:"requestId"`
	UrlCallback *string `json:"urlCallback,omitempty"`
	AdresseIp string `json:"adresseIp"`
}

type _AchatEnLigneModel AchatEnLigneModel

// NewAchatEnLigneModel instantiates a new AchatEnLigneModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAchatEnLigneModel(descriptionAchat []string, montantTransaction float64, phoneClient string, motifTransaction string, requestId string, adresseIp string) *AchatEnLigneModel {
	this := AchatEnLigneModel{}
	this.DescriptionAchat = descriptionAchat
	this.MontantTransaction = montantTransaction
	this.PhoneClient = phoneClient
	this.MotifTransaction = motifTransaction
	this.RequestId = requestId
	this.AdresseIp = adresseIp
	return &this
}

// NewAchatEnLigneModelWithDefaults instantiates a new AchatEnLigneModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAchatEnLigneModelWithDefaults() *AchatEnLigneModel {
	this := AchatEnLigneModel{}
	return &this
}

// GetDescriptionAchat returns the DescriptionAchat field value
func (o *AchatEnLigneModel) GetDescriptionAchat() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.DescriptionAchat
}

// GetDescriptionAchatOk returns a tuple with the DescriptionAchat field value
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetDescriptionAchatOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DescriptionAchat, true
}

// SetDescriptionAchat sets field value
func (o *AchatEnLigneModel) SetDescriptionAchat(v []string) {
	o.DescriptionAchat = v
}

// GetMontantTransaction returns the MontantTransaction field value
func (o *AchatEnLigneModel) GetMontantTransaction() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.MontantTransaction
}

// GetMontantTransactionOk returns a tuple with the MontantTransaction field value
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetMontantTransactionOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MontantTransaction, true
}

// SetMontantTransaction sets field value
func (o *AchatEnLigneModel) SetMontantTransaction(v float64) {
	o.MontantTransaction = v
}

// GetPhoneClient returns the PhoneClient field value
func (o *AchatEnLigneModel) GetPhoneClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneClient
}

// GetPhoneClientOk returns a tuple with the PhoneClient field value
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetPhoneClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneClient, true
}

// SetPhoneClient sets field value
func (o *AchatEnLigneModel) SetPhoneClient(v string) {
	o.PhoneClient = v
}

// GetMotifTransaction returns the MotifTransaction field value
func (o *AchatEnLigneModel) GetMotifTransaction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MotifTransaction
}

// GetMotifTransactionOk returns a tuple with the MotifTransaction field value
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetMotifTransactionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MotifTransaction, true
}

// SetMotifTransaction sets field value
func (o *AchatEnLigneModel) SetMotifTransaction(v string) {
	o.MotifTransaction = v
}

// GetLongTransaction returns the LongTransaction field value if set, zero value otherwise.
func (o *AchatEnLigneModel) GetLongTransaction() string {
	if o == nil || IsNil(o.LongTransaction) {
		var ret string
		return ret
	}
	return *o.LongTransaction
}

// GetLongTransactionOk returns a tuple with the LongTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetLongTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.LongTransaction) {
		return nil, false
	}
	return o.LongTransaction, true
}

// HasLongTransaction returns a boolean if a field has been set.
func (o *AchatEnLigneModel) HasLongTransaction() bool {
	if o != nil && !IsNil(o.LongTransaction) {
		return true
	}

	return false
}

// SetLongTransaction gets a reference to the given string and assigns it to the LongTransaction field.
func (o *AchatEnLigneModel) SetLongTransaction(v string) {
	o.LongTransaction = &v
}

// GetLatTransaction returns the LatTransaction field value if set, zero value otherwise.
func (o *AchatEnLigneModel) GetLatTransaction() string {
	if o == nil || IsNil(o.LatTransaction) {
		var ret string
		return ret
	}
	return *o.LatTransaction
}

// GetLatTransactionOk returns a tuple with the LatTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetLatTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.LatTransaction) {
		return nil, false
	}
	return o.LatTransaction, true
}

// HasLatTransaction returns a boolean if a field has been set.
func (o *AchatEnLigneModel) HasLatTransaction() bool {
	if o != nil && !IsNil(o.LatTransaction) {
		return true
	}

	return false
}

// SetLatTransaction gets a reference to the given string and assigns it to the LatTransaction field.
func (o *AchatEnLigneModel) SetLatTransaction(v string) {
	o.LatTransaction = &v
}

// GetRequestId returns the RequestId field value
func (o *AchatEnLigneModel) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *AchatEnLigneModel) SetRequestId(v string) {
	o.RequestId = v
}

// GetUrlCallback returns the UrlCallback field value if set, zero value otherwise.
func (o *AchatEnLigneModel) GetUrlCallback() string {
	if o == nil || IsNil(o.UrlCallback) {
		var ret string
		return ret
	}
	return *o.UrlCallback
}

// GetUrlCallbackOk returns a tuple with the UrlCallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetUrlCallbackOk() (*string, bool) {
	if o == nil || IsNil(o.UrlCallback) {
		return nil, false
	}
	return o.UrlCallback, true
}

// HasUrlCallback returns a boolean if a field has been set.
func (o *AchatEnLigneModel) HasUrlCallback() bool {
	if o != nil && !IsNil(o.UrlCallback) {
		return true
	}

	return false
}

// SetUrlCallback gets a reference to the given string and assigns it to the UrlCallback field.
func (o *AchatEnLigneModel) SetUrlCallback(v string) {
	o.UrlCallback = &v
}

// GetAdresseIp returns the AdresseIp field value
func (o *AchatEnLigneModel) GetAdresseIp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AdresseIp
}

// GetAdresseIpOk returns a tuple with the AdresseIp field value
// and a boolean to check if the value has been set.
func (o *AchatEnLigneModel) GetAdresseIpOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AdresseIp, true
}

// SetAdresseIp sets field value
func (o *AchatEnLigneModel) SetAdresseIp(v string) {
	o.AdresseIp = v
}

func (o AchatEnLigneModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AchatEnLigneModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["descriptionAchat"] = o.DescriptionAchat
	toSerialize["montantTransaction"] = o.MontantTransaction
	toSerialize["phoneClient"] = o.PhoneClient
	toSerialize["motifTransaction"] = o.MotifTransaction
	if !IsNil(o.LongTransaction) {
		toSerialize["longTransaction"] = o.LongTransaction
	}
	if !IsNil(o.LatTransaction) {
		toSerialize["latTransaction"] = o.LatTransaction
	}
	toSerialize["requestId"] = o.RequestId
	if !IsNil(o.UrlCallback) {
		toSerialize["urlCallback"] = o.UrlCallback
	}
	toSerialize["adresseIp"] = o.AdresseIp
	return toSerialize, nil
}

func (o *AchatEnLigneModel) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"descriptionAchat",
		"montantTransaction",
		"phoneClient",
		"motifTransaction",
		"requestId",
		"adresseIp",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAchatEnLigneModel := _AchatEnLigneModel{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAchatEnLigneModel)

	if err != nil {
		return err
	}

	*o = AchatEnLigneModel(varAchatEnLigneModel)

	return err
}

type NullableAchatEnLigneModel struct {
	value *AchatEnLigneModel
	isSet bool
}

func (v NullableAchatEnLigneModel) Get() *AchatEnLigneModel {
	return v.value
}

func (v *NullableAchatEnLigneModel) Set(val *AchatEnLigneModel) {
	v.value = val
	v.isSet = true
}

func (v NullableAchatEnLigneModel) IsSet() bool {
	return v.isSet
}

func (v *NullableAchatEnLigneModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAchatEnLigneModel(val *AchatEnLigneModel) *NullableAchatEnLigneModel {
	return &NullableAchatEnLigneModel{value: val, isSet: true}
}

func (v NullableAchatEnLigneModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAchatEnLigneModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


