/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the IndicatifsResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IndicatifsResponseV2{}

// IndicatifsResponseV2 struct for IndicatifsResponseV2
type IndicatifsResponseV2 struct {
	PaysActifs []IndicatifResponse `json:"paysActifs,omitempty"`
}

// NewIndicatifsResponseV2 instantiates a new IndicatifsResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIndicatifsResponseV2() *IndicatifsResponseV2 {
	this := IndicatifsResponseV2{}
	return &this
}

// NewIndicatifsResponseV2WithDefaults instantiates a new IndicatifsResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIndicatifsResponseV2WithDefaults() *IndicatifsResponseV2 {
	this := IndicatifsResponseV2{}
	return &this
}

// GetPaysActifs returns the PaysActifs field value if set, zero value otherwise.
func (o *IndicatifsResponseV2) GetPaysActifs() []IndicatifResponse {
	if o == nil || IsNil(o.PaysActifs) {
		var ret []IndicatifResponse
		return ret
	}
	return o.PaysActifs
}

// GetPaysActifsOk returns a tuple with the PaysActifs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IndicatifsResponseV2) GetPaysActifsOk() ([]IndicatifResponse, bool) {
	if o == nil || IsNil(o.PaysActifs) {
		return nil, false
	}
	return o.PaysActifs, true
}

// HasPaysActifs returns a boolean if a field has been set.
func (o *IndicatifsResponseV2) HasPaysActifs() bool {
	if o != nil && !IsNil(o.PaysActifs) {
		return true
	}

	return false
}

// SetPaysActifs gets a reference to the given []IndicatifResponse and assigns it to the PaysActifs field.
func (o *IndicatifsResponseV2) SetPaysActifs(v []IndicatifResponse) {
	o.PaysActifs = v
}

func (o IndicatifsResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IndicatifsResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PaysActifs) {
		toSerialize["paysActifs"] = o.PaysActifs
	}
	return toSerialize, nil
}

type NullableIndicatifsResponseV2 struct {
	value *IndicatifsResponseV2
	isSet bool
}

func (v NullableIndicatifsResponseV2) Get() *IndicatifsResponseV2 {
	return v.value
}

func (v *NullableIndicatifsResponseV2) Set(val *IndicatifsResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableIndicatifsResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableIndicatifsResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIndicatifsResponseV2(val *IndicatifsResponseV2) *NullableIndicatifsResponseV2 {
	return &NullableIndicatifsResponseV2{value: val, isSet: true}
}

func (v NullableIndicatifsResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIndicatifsResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


