/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the VilleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VilleResponse{}

// VilleResponse struct for VilleResponse
type VilleResponse struct {
	Nom *string `json:"nom,omitempty"`
	Pays *string `json:"pays,omitempty"`
}

// NewVilleResponse instantiates a new VilleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVilleResponse() *VilleResponse {
	this := VilleResponse{}
	return &this
}

// NewVilleResponseWithDefaults instantiates a new VilleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVilleResponseWithDefaults() *VilleResponse {
	this := VilleResponse{}
	return &this
}

// GetNom returns the Nom field value if set, zero value otherwise.
func (o *VilleResponse) GetNom() string {
	if o == nil || IsNil(o.Nom) {
		var ret string
		return ret
	}
	return *o.Nom
}

// GetNomOk returns a tuple with the Nom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VilleResponse) GetNomOk() (*string, bool) {
	if o == nil || IsNil(o.Nom) {
		return nil, false
	}
	return o.Nom, true
}

// HasNom returns a boolean if a field has been set.
func (o *VilleResponse) HasNom() bool {
	if o != nil && !IsNil(o.Nom) {
		return true
	}

	return false
}

// SetNom gets a reference to the given string and assigns it to the Nom field.
func (o *VilleResponse) SetNom(v string) {
	o.Nom = &v
}

// GetPays returns the Pays field value if set, zero value otherwise.
func (o *VilleResponse) GetPays() string {
	if o == nil || IsNil(o.Pays) {
		var ret string
		return ret
	}
	return *o.Pays
}

// GetPaysOk returns a tuple with the Pays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VilleResponse) GetPaysOk() (*string, bool) {
	if o == nil || IsNil(o.Pays) {
		return nil, false
	}
	return o.Pays, true
}

// HasPays returns a boolean if a field has been set.
func (o *VilleResponse) HasPays() bool {
	if o != nil && !IsNil(o.Pays) {
		return true
	}

	return false
}

// SetPays gets a reference to the given string and assigns it to the Pays field.
func (o *VilleResponse) SetPays(v string) {
	o.Pays = &v
}

func (o VilleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VilleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Nom) {
		toSerialize["nom"] = o.Nom
	}
	if !IsNil(o.Pays) {
		toSerialize["pays"] = o.Pays
	}
	return toSerialize, nil
}

type NullableVilleResponse struct {
	value *VilleResponse
	isSet bool
}

func (v NullableVilleResponse) Get() *VilleResponse {
	return v.value
}

func (v *NullableVilleResponse) Set(val *VilleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVilleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVilleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVilleResponse(val *VilleResponse) *NullableVilleResponse {
	return &NullableVilleResponse{value: val, isSet: true}
}

func (v NullableVilleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVilleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


