/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnvoiToEditDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnvoiToEditDto{}

// EnvoiToEditDto struct for EnvoiToEditDto
type EnvoiToEditDto struct {
	CodeEnvoi string `json:"codeEnvoi"`
	RequestId string `json:"requestId"`
	IndicatifExpediteur string `json:"indicatifExpediteur" validate:"regexp=^\\\\+?\\\\d{2,6}$"`
	NumeroExpediteur string `json:"numeroExpediteur" validate:"regexp=^\\\\d{4,15}$"`
}

type _EnvoiToEditDto EnvoiToEditDto

// NewEnvoiToEditDto instantiates a new EnvoiToEditDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvoiToEditDto(codeEnvoi string, requestId string, indicatifExpediteur string, numeroExpediteur string) *EnvoiToEditDto {
	this := EnvoiToEditDto{}
	this.CodeEnvoi = codeEnvoi
	this.RequestId = requestId
	this.IndicatifExpediteur = indicatifExpediteur
	this.NumeroExpediteur = numeroExpediteur
	return &this
}

// NewEnvoiToEditDtoWithDefaults instantiates a new EnvoiToEditDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvoiToEditDtoWithDefaults() *EnvoiToEditDto {
	this := EnvoiToEditDto{}
	return &this
}

// GetCodeEnvoi returns the CodeEnvoi field value
func (o *EnvoiToEditDto) GetCodeEnvoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeEnvoi
}

// GetCodeEnvoiOk returns a tuple with the CodeEnvoi field value
// and a boolean to check if the value has been set.
func (o *EnvoiToEditDto) GetCodeEnvoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeEnvoi, true
}

// SetCodeEnvoi sets field value
func (o *EnvoiToEditDto) SetCodeEnvoi(v string) {
	o.CodeEnvoi = v
}

// GetRequestId returns the RequestId field value
func (o *EnvoiToEditDto) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *EnvoiToEditDto) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *EnvoiToEditDto) SetRequestId(v string) {
	o.RequestId = v
}

// GetIndicatifExpediteur returns the IndicatifExpediteur field value
func (o *EnvoiToEditDto) GetIndicatifExpediteur() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndicatifExpediteur
}

// GetIndicatifExpediteurOk returns a tuple with the IndicatifExpediteur field value
// and a boolean to check if the value has been set.
func (o *EnvoiToEditDto) GetIndicatifExpediteurOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndicatifExpediteur, true
}

// SetIndicatifExpediteur sets field value
func (o *EnvoiToEditDto) SetIndicatifExpediteur(v string) {
	o.IndicatifExpediteur = v
}

// GetNumeroExpediteur returns the NumeroExpediteur field value
func (o *EnvoiToEditDto) GetNumeroExpediteur() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NumeroExpediteur
}

// GetNumeroExpediteurOk returns a tuple with the NumeroExpediteur field value
// and a boolean to check if the value has been set.
func (o *EnvoiToEditDto) GetNumeroExpediteurOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumeroExpediteur, true
}

// SetNumeroExpediteur sets field value
func (o *EnvoiToEditDto) SetNumeroExpediteur(v string) {
	o.NumeroExpediteur = v
}

func (o EnvoiToEditDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnvoiToEditDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codeEnvoi"] = o.CodeEnvoi
	toSerialize["requestId"] = o.RequestId
	toSerialize["indicatifExpediteur"] = o.IndicatifExpediteur
	toSerialize["numeroExpediteur"] = o.NumeroExpediteur
	return toSerialize, nil
}

func (o *EnvoiToEditDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codeEnvoi",
		"requestId",
		"indicatifExpediteur",
		"numeroExpediteur",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnvoiToEditDto := _EnvoiToEditDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnvoiToEditDto)

	if err != nil {
		return err
	}

	*o = EnvoiToEditDto(varEnvoiToEditDto)

	return err
}

type NullableEnvoiToEditDto struct {
	value *EnvoiToEditDto
	isSet bool
}

func (v NullableEnvoiToEditDto) Get() *EnvoiToEditDto {
	return v.value
}

func (v *NullableEnvoiToEditDto) Set(val *EnvoiToEditDto) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvoiToEditDto) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvoiToEditDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvoiToEditDto(val *EnvoiToEditDto) *NullableEnvoiToEditDto {
	return &NullableEnvoiToEditDto{value: val, isSet: true}
}

func (v NullableEnvoiToEditDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvoiToEditDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


