/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CalculeFraisOperationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalculeFraisOperationRequest{}

// CalculeFraisOperationRequest Détails pour le calcul des frais d'envoi
type CalculeFraisOperationRequest struct {
	IndicatifExpediteur string `json:"indicatifExpediteur" validate:"regexp=^\\\\+?\\\\d{2,6}$"`
	NumeroExpediteur string `json:"numeroExpediteur" validate:"regexp=^\\\\d{4,15}$"`
	Montant float64 `json:"montant"`
	FraisInclus bool `json:"fraisInclus"`
	VilleExpedition string `json:"villeExpedition"`
	VilleDestination string `json:"villeDestination"`
	// Grille tarifaire du reseau de retrait cash : CCP (Niger Poste, defaut) ou BIN.
	Profil *string `json:"profil,omitempty"`
}

type _CalculeFraisOperationRequest CalculeFraisOperationRequest

// NewCalculeFraisOperationRequest instantiates a new CalculeFraisOperationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalculeFraisOperationRequest(indicatifExpediteur string, numeroExpediteur string, montant float64, fraisInclus bool, villeExpedition string, villeDestination string) *CalculeFraisOperationRequest {
	this := CalculeFraisOperationRequest{}
	this.IndicatifExpediteur = indicatifExpediteur
	this.NumeroExpediteur = numeroExpediteur
	this.Montant = montant
	this.FraisInclus = fraisInclus
	this.VilleExpedition = villeExpedition
	this.VilleDestination = villeDestination
	var profil string = "CCP"
	this.Profil = &profil
	return &this
}

// NewCalculeFraisOperationRequestWithDefaults instantiates a new CalculeFraisOperationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalculeFraisOperationRequestWithDefaults() *CalculeFraisOperationRequest {
	this := CalculeFraisOperationRequest{}
	var profil string = "CCP"
	this.Profil = &profil
	return &this
}

// GetIndicatifExpediteur returns the IndicatifExpediteur field value
func (o *CalculeFraisOperationRequest) GetIndicatifExpediteur() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndicatifExpediteur
}

// GetIndicatifExpediteurOk returns a tuple with the IndicatifExpediteur field value
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetIndicatifExpediteurOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndicatifExpediteur, true
}

// SetIndicatifExpediteur sets field value
func (o *CalculeFraisOperationRequest) SetIndicatifExpediteur(v string) {
	o.IndicatifExpediteur = v
}

// GetNumeroExpediteur returns the NumeroExpediteur field value
func (o *CalculeFraisOperationRequest) GetNumeroExpediteur() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NumeroExpediteur
}

// GetNumeroExpediteurOk returns a tuple with the NumeroExpediteur field value
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetNumeroExpediteurOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumeroExpediteur, true
}

// SetNumeroExpediteur sets field value
func (o *CalculeFraisOperationRequest) SetNumeroExpediteur(v string) {
	o.NumeroExpediteur = v
}

// GetMontant returns the Montant field value
func (o *CalculeFraisOperationRequest) GetMontant() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Montant
}

// GetMontantOk returns a tuple with the Montant field value
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetMontantOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Montant, true
}

// SetMontant sets field value
func (o *CalculeFraisOperationRequest) SetMontant(v float64) {
	o.Montant = v
}

// GetFraisInclus returns the FraisInclus field value
func (o *CalculeFraisOperationRequest) GetFraisInclus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.FraisInclus
}

// GetFraisInclusOk returns a tuple with the FraisInclus field value
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetFraisInclusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FraisInclus, true
}

// SetFraisInclus sets field value
func (o *CalculeFraisOperationRequest) SetFraisInclus(v bool) {
	o.FraisInclus = v
}

// GetVilleExpedition returns the VilleExpedition field value
func (o *CalculeFraisOperationRequest) GetVilleExpedition() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VilleExpedition
}

// GetVilleExpeditionOk returns a tuple with the VilleExpedition field value
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetVilleExpeditionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VilleExpedition, true
}

// SetVilleExpedition sets field value
func (o *CalculeFraisOperationRequest) SetVilleExpedition(v string) {
	o.VilleExpedition = v
}

// GetVilleDestination returns the VilleDestination field value
func (o *CalculeFraisOperationRequest) GetVilleDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VilleDestination
}

// GetVilleDestinationOk returns a tuple with the VilleDestination field value
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetVilleDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VilleDestination, true
}

// SetVilleDestination sets field value
func (o *CalculeFraisOperationRequest) SetVilleDestination(v string) {
	o.VilleDestination = v
}

// GetProfil returns the Profil field value if set, zero value otherwise.
func (o *CalculeFraisOperationRequest) GetProfil() string {
	if o == nil || IsNil(o.Profil) {
		var ret string
		return ret
	}
	return *o.Profil
}

// GetProfilOk returns a tuple with the Profil field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalculeFraisOperationRequest) GetProfilOk() (*string, bool) {
	if o == nil || IsNil(o.Profil) {
		return nil, false
	}
	return o.Profil, true
}

// HasProfil returns a boolean if a field has been set.
func (o *CalculeFraisOperationRequest) HasProfil() bool {
	if o != nil && !IsNil(o.Profil) {
		return true
	}

	return false
}

// SetProfil gets a reference to the given string and assigns it to the Profil field.
func (o *CalculeFraisOperationRequest) SetProfil(v string) {
	o.Profil = &v
}

func (o CalculeFraisOperationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalculeFraisOperationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["indicatifExpediteur"] = o.IndicatifExpediteur
	toSerialize["numeroExpediteur"] = o.NumeroExpediteur
	toSerialize["montant"] = o.Montant
	toSerialize["fraisInclus"] = o.FraisInclus
	toSerialize["villeExpedition"] = o.VilleExpedition
	toSerialize["villeDestination"] = o.VilleDestination
	if !IsNil(o.Profil) {
		toSerialize["profil"] = o.Profil
	}
	return toSerialize, nil
}

func (o *CalculeFraisOperationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"indicatifExpediteur",
		"numeroExpediteur",
		"montant",
		"fraisInclus",
		"villeExpedition",
		"villeDestination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalculeFraisOperationRequest := _CalculeFraisOperationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalculeFraisOperationRequest)

	if err != nil {
		return err
	}

	*o = CalculeFraisOperationRequest(varCalculeFraisOperationRequest)

	return err
}

type NullableCalculeFraisOperationRequest struct {
	value *CalculeFraisOperationRequest
	isSet bool
}

func (v NullableCalculeFraisOperationRequest) Get() *CalculeFraisOperationRequest {
	return v.value
}

func (v *NullableCalculeFraisOperationRequest) Set(val *CalculeFraisOperationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCalculeFraisOperationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCalculeFraisOperationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalculeFraisOperationRequest(val *CalculeFraisOperationRequest) *NullableCalculeFraisOperationRequest {
	return &NullableCalculeFraisOperationRequest{value: val, isSet: true}
}

func (v NullableCalculeFraisOperationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalculeFraisOperationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


