/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"time"
)

// checks if the TransactionResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionResponseV2{}

// TransactionResponseV2 struct for TransactionResponseV2
type TransactionResponseV2 struct {
	PublicId *string `json:"publicId,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	CodeEnvoi *string `json:"codeEnvoi,omitempty"`
	Montant *float64 `json:"montant,omitempty"`
	FraisEnvoi *float64 `json:"fraisEnvoi,omitempty"`
	Reduction *float64 `json:"reduction,omitempty"`
	FraisInclus *bool `json:"fraisInclus,omitempty"`
	Total *float64 `json:"total,omitempty"`
	StatusTransaction *string `json:"statusTransaction,omitempty"`
	TypeTransaction *string `json:"typeTransaction,omitempty"`
	TypeOperation *string `json:"typeOperation,omitempty"`
	NomExpediteur *string `json:"nomExpediteur,omitempty"`
	PrenomExpediteur *string `json:"prenomExpediteur,omitempty"`
	TelephoneExpediteur *string `json:"telephoneExpediteur,omitempty"`
	NomDestinataire *string `json:"nomDestinataire,omitempty"`
	PrenomDestinataire *string `json:"prenomDestinataire,omitempty"`
	TelephoneDestinataire *string `json:"telephoneDestinataire,omitempty"`
	VilleDestinataire *string `json:"villeDestinataire,omitempty"`
	PaysDestinataire *string `json:"paysDestinataire,omitempty"`
	DateTransaction *time.Time `json:"dateTransaction,omitempty"`
}

// NewTransactionResponseV2 instantiates a new TransactionResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionResponseV2() *TransactionResponseV2 {
	this := TransactionResponseV2{}
	return &this
}

// NewTransactionResponseV2WithDefaults instantiates a new TransactionResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionResponseV2WithDefaults() *TransactionResponseV2 {
	this := TransactionResponseV2{}
	return &this
}

// GetPublicId returns the PublicId field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetPublicId() string {
	if o == nil || IsNil(o.PublicId) {
		var ret string
		return ret
	}
	return *o.PublicId
}

// GetPublicIdOk returns a tuple with the PublicId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetPublicIdOk() (*string, bool) {
	if o == nil || IsNil(o.PublicId) {
		return nil, false
	}
	return o.PublicId, true
}

// HasPublicId returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasPublicId() bool {
	if o != nil && !IsNil(o.PublicId) {
		return true
	}

	return false
}

// SetPublicId gets a reference to the given string and assigns it to the PublicId field.
func (o *TransactionResponseV2) SetPublicId(v string) {
	o.PublicId = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *TransactionResponseV2) SetRequestId(v string) {
	o.RequestId = &v
}

// GetCodeEnvoi returns the CodeEnvoi field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetCodeEnvoi() string {
	if o == nil || IsNil(o.CodeEnvoi) {
		var ret string
		return ret
	}
	return *o.CodeEnvoi
}

// GetCodeEnvoiOk returns a tuple with the CodeEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetCodeEnvoiOk() (*string, bool) {
	if o == nil || IsNil(o.CodeEnvoi) {
		return nil, false
	}
	return o.CodeEnvoi, true
}

// HasCodeEnvoi returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasCodeEnvoi() bool {
	if o != nil && !IsNil(o.CodeEnvoi) {
		return true
	}

	return false
}

// SetCodeEnvoi gets a reference to the given string and assigns it to the CodeEnvoi field.
func (o *TransactionResponseV2) SetCodeEnvoi(v string) {
	o.CodeEnvoi = &v
}

// GetMontant returns the Montant field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetMontant() float64 {
	if o == nil || IsNil(o.Montant) {
		var ret float64
		return ret
	}
	return *o.Montant
}

// GetMontantOk returns a tuple with the Montant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetMontantOk() (*float64, bool) {
	if o == nil || IsNil(o.Montant) {
		return nil, false
	}
	return o.Montant, true
}

// HasMontant returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasMontant() bool {
	if o != nil && !IsNil(o.Montant) {
		return true
	}

	return false
}

// SetMontant gets a reference to the given float64 and assigns it to the Montant field.
func (o *TransactionResponseV2) SetMontant(v float64) {
	o.Montant = &v
}

// GetFraisEnvoi returns the FraisEnvoi field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetFraisEnvoi() float64 {
	if o == nil || IsNil(o.FraisEnvoi) {
		var ret float64
		return ret
	}
	return *o.FraisEnvoi
}

// GetFraisEnvoiOk returns a tuple with the FraisEnvoi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetFraisEnvoiOk() (*float64, bool) {
	if o == nil || IsNil(o.FraisEnvoi) {
		return nil, false
	}
	return o.FraisEnvoi, true
}

// HasFraisEnvoi returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasFraisEnvoi() bool {
	if o != nil && !IsNil(o.FraisEnvoi) {
		return true
	}

	return false
}

// SetFraisEnvoi gets a reference to the given float64 and assigns it to the FraisEnvoi field.
func (o *TransactionResponseV2) SetFraisEnvoi(v float64) {
	o.FraisEnvoi = &v
}

// GetReduction returns the Reduction field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetReduction() float64 {
	if o == nil || IsNil(o.Reduction) {
		var ret float64
		return ret
	}
	return *o.Reduction
}

// GetReductionOk returns a tuple with the Reduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetReductionOk() (*float64, bool) {
	if o == nil || IsNil(o.Reduction) {
		return nil, false
	}
	return o.Reduction, true
}

// HasReduction returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasReduction() bool {
	if o != nil && !IsNil(o.Reduction) {
		return true
	}

	return false
}

// SetReduction gets a reference to the given float64 and assigns it to the Reduction field.
func (o *TransactionResponseV2) SetReduction(v float64) {
	o.Reduction = &v
}

// GetFraisInclus returns the FraisInclus field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetFraisInclus() bool {
	if o == nil || IsNil(o.FraisInclus) {
		var ret bool
		return ret
	}
	return *o.FraisInclus
}

// GetFraisInclusOk returns a tuple with the FraisInclus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetFraisInclusOk() (*bool, bool) {
	if o == nil || IsNil(o.FraisInclus) {
		return nil, false
	}
	return o.FraisInclus, true
}

// HasFraisInclus returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasFraisInclus() bool {
	if o != nil && !IsNil(o.FraisInclus) {
		return true
	}

	return false
}

// SetFraisInclus gets a reference to the given bool and assigns it to the FraisInclus field.
func (o *TransactionResponseV2) SetFraisInclus(v bool) {
	o.FraisInclus = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetTotal() float64 {
	if o == nil || IsNil(o.Total) {
		var ret float64
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetTotalOk() (*float64, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float64 and assigns it to the Total field.
func (o *TransactionResponseV2) SetTotal(v float64) {
	o.Total = &v
}

// GetStatusTransaction returns the StatusTransaction field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetStatusTransaction() string {
	if o == nil || IsNil(o.StatusTransaction) {
		var ret string
		return ret
	}
	return *o.StatusTransaction
}

// GetStatusTransactionOk returns a tuple with the StatusTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetStatusTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.StatusTransaction) {
		return nil, false
	}
	return o.StatusTransaction, true
}

// HasStatusTransaction returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasStatusTransaction() bool {
	if o != nil && !IsNil(o.StatusTransaction) {
		return true
	}

	return false
}

// SetStatusTransaction gets a reference to the given string and assigns it to the StatusTransaction field.
func (o *TransactionResponseV2) SetStatusTransaction(v string) {
	o.StatusTransaction = &v
}

// GetTypeTransaction returns the TypeTransaction field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetTypeTransaction() string {
	if o == nil || IsNil(o.TypeTransaction) {
		var ret string
		return ret
	}
	return *o.TypeTransaction
}

// GetTypeTransactionOk returns a tuple with the TypeTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetTypeTransactionOk() (*string, bool) {
	if o == nil || IsNil(o.TypeTransaction) {
		return nil, false
	}
	return o.TypeTransaction, true
}

// HasTypeTransaction returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasTypeTransaction() bool {
	if o != nil && !IsNil(o.TypeTransaction) {
		return true
	}

	return false
}

// SetTypeTransaction gets a reference to the given string and assigns it to the TypeTransaction field.
func (o *TransactionResponseV2) SetTypeTransaction(v string) {
	o.TypeTransaction = &v
}

// GetTypeOperation returns the TypeOperation field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetTypeOperation() string {
	if o == nil || IsNil(o.TypeOperation) {
		var ret string
		return ret
	}
	return *o.TypeOperation
}

// GetTypeOperationOk returns a tuple with the TypeOperation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetTypeOperationOk() (*string, bool) {
	if o == nil || IsNil(o.TypeOperation) {
		return nil, false
	}
	return o.TypeOperation, true
}

// HasTypeOperation returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasTypeOperation() bool {
	if o != nil && !IsNil(o.TypeOperation) {
		return true
	}

	return false
}

// SetTypeOperation gets a reference to the given string and assigns it to the TypeOperation field.
func (o *TransactionResponseV2) SetTypeOperation(v string) {
	o.TypeOperation = &v
}

// GetNomExpediteur returns the NomExpediteur field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetNomExpediteur() string {
	if o == nil || IsNil(o.NomExpediteur) {
		var ret string
		return ret
	}
	return *o.NomExpediteur
}

// GetNomExpediteurOk returns a tuple with the NomExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetNomExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.NomExpediteur) {
		return nil, false
	}
	return o.NomExpediteur, true
}

// HasNomExpediteur returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasNomExpediteur() bool {
	if o != nil && !IsNil(o.NomExpediteur) {
		return true
	}

	return false
}

// SetNomExpediteur gets a reference to the given string and assigns it to the NomExpediteur field.
func (o *TransactionResponseV2) SetNomExpediteur(v string) {
	o.NomExpediteur = &v
}

// GetPrenomExpediteur returns the PrenomExpediteur field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetPrenomExpediteur() string {
	if o == nil || IsNil(o.PrenomExpediteur) {
		var ret string
		return ret
	}
	return *o.PrenomExpediteur
}

// GetPrenomExpediteurOk returns a tuple with the PrenomExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetPrenomExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomExpediteur) {
		return nil, false
	}
	return o.PrenomExpediteur, true
}

// HasPrenomExpediteur returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasPrenomExpediteur() bool {
	if o != nil && !IsNil(o.PrenomExpediteur) {
		return true
	}

	return false
}

// SetPrenomExpediteur gets a reference to the given string and assigns it to the PrenomExpediteur field.
func (o *TransactionResponseV2) SetPrenomExpediteur(v string) {
	o.PrenomExpediteur = &v
}

// GetTelephoneExpediteur returns the TelephoneExpediteur field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetTelephoneExpediteur() string {
	if o == nil || IsNil(o.TelephoneExpediteur) {
		var ret string
		return ret
	}
	return *o.TelephoneExpediteur
}

// GetTelephoneExpediteurOk returns a tuple with the TelephoneExpediteur field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetTelephoneExpediteurOk() (*string, bool) {
	if o == nil || IsNil(o.TelephoneExpediteur) {
		return nil, false
	}
	return o.TelephoneExpediteur, true
}

// HasTelephoneExpediteur returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasTelephoneExpediteur() bool {
	if o != nil && !IsNil(o.TelephoneExpediteur) {
		return true
	}

	return false
}

// SetTelephoneExpediteur gets a reference to the given string and assigns it to the TelephoneExpediteur field.
func (o *TransactionResponseV2) SetTelephoneExpediteur(v string) {
	o.TelephoneExpediteur = &v
}

// GetNomDestinataire returns the NomDestinataire field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetNomDestinataire() string {
	if o == nil || IsNil(o.NomDestinataire) {
		var ret string
		return ret
	}
	return *o.NomDestinataire
}

// GetNomDestinataireOk returns a tuple with the NomDestinataire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetNomDestinataireOk() (*string, bool) {
	if o == nil || IsNil(o.NomDestinataire) {
		return nil, false
	}
	return o.NomDestinataire, true
}

// HasNomDestinataire returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasNomDestinataire() bool {
	if o != nil && !IsNil(o.NomDestinataire) {
		return true
	}

	return false
}

// SetNomDestinataire gets a reference to the given string and assigns it to the NomDestinataire field.
func (o *TransactionResponseV2) SetNomDestinataire(v string) {
	o.NomDestinataire = &v
}

// GetPrenomDestinataire returns the PrenomDestinataire field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetPrenomDestinataire() string {
	if o == nil || IsNil(o.PrenomDestinataire) {
		var ret string
		return ret
	}
	return *o.PrenomDestinataire
}

// GetPrenomDestinataireOk returns a tuple with the PrenomDestinataire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetPrenomDestinataireOk() (*string, bool) {
	if o == nil || IsNil(o.PrenomDestinataire) {
		return nil, false
	}
	return o.PrenomDestinataire, true
}

// HasPrenomDestinataire returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasPrenomDestinataire() bool {
	if o != nil && !IsNil(o.PrenomDestinataire) {
		return true
	}

	return false
}

// SetPrenomDestinataire gets a reference to the given string and assigns it to the PrenomDestinataire field.
func (o *TransactionResponseV2) SetPrenomDestinataire(v string) {
	o.PrenomDestinataire = &v
}

// GetTelephoneDestinataire returns the TelephoneDestinataire field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetTelephoneDestinataire() string {
	if o == nil || IsNil(o.TelephoneDestinataire) {
		var ret string
		return ret
	}
	return *o.TelephoneDestinataire
}

// GetTelephoneDestinataireOk returns a tuple with the TelephoneDestinataire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetTelephoneDestinataireOk() (*string, bool) {
	if o == nil || IsNil(o.TelephoneDestinataire) {
		return nil, false
	}
	return o.TelephoneDestinataire, true
}

// HasTelephoneDestinataire returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasTelephoneDestinataire() bool {
	if o != nil && !IsNil(o.TelephoneDestinataire) {
		return true
	}

	return false
}

// SetTelephoneDestinataire gets a reference to the given string and assigns it to the TelephoneDestinataire field.
func (o *TransactionResponseV2) SetTelephoneDestinataire(v string) {
	o.TelephoneDestinataire = &v
}

// GetVilleDestinataire returns the VilleDestinataire field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetVilleDestinataire() string {
	if o == nil || IsNil(o.VilleDestinataire) {
		var ret string
		return ret
	}
	return *o.VilleDestinataire
}

// GetVilleDestinataireOk returns a tuple with the VilleDestinataire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetVilleDestinataireOk() (*string, bool) {
	if o == nil || IsNil(o.VilleDestinataire) {
		return nil, false
	}
	return o.VilleDestinataire, true
}

// HasVilleDestinataire returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasVilleDestinataire() bool {
	if o != nil && !IsNil(o.VilleDestinataire) {
		return true
	}

	return false
}

// SetVilleDestinataire gets a reference to the given string and assigns it to the VilleDestinataire field.
func (o *TransactionResponseV2) SetVilleDestinataire(v string) {
	o.VilleDestinataire = &v
}

// GetPaysDestinataire returns the PaysDestinataire field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetPaysDestinataire() string {
	if o == nil || IsNil(o.PaysDestinataire) {
		var ret string
		return ret
	}
	return *o.PaysDestinataire
}

// GetPaysDestinataireOk returns a tuple with the PaysDestinataire field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetPaysDestinataireOk() (*string, bool) {
	if o == nil || IsNil(o.PaysDestinataire) {
		return nil, false
	}
	return o.PaysDestinataire, true
}

// HasPaysDestinataire returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasPaysDestinataire() bool {
	if o != nil && !IsNil(o.PaysDestinataire) {
		return true
	}

	return false
}

// SetPaysDestinataire gets a reference to the given string and assigns it to the PaysDestinataire field.
func (o *TransactionResponseV2) SetPaysDestinataire(v string) {
	o.PaysDestinataire = &v
}

// GetDateTransaction returns the DateTransaction field value if set, zero value otherwise.
func (o *TransactionResponseV2) GetDateTransaction() time.Time {
	if o == nil || IsNil(o.DateTransaction) {
		var ret time.Time
		return ret
	}
	return *o.DateTransaction
}

// GetDateTransactionOk returns a tuple with the DateTransaction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionResponseV2) GetDateTransactionOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DateTransaction) {
		return nil, false
	}
	return o.DateTransaction, true
}

// HasDateTransaction returns a boolean if a field has been set.
func (o *TransactionResponseV2) HasDateTransaction() bool {
	if o != nil && !IsNil(o.DateTransaction) {
		return true
	}

	return false
}

// SetDateTransaction gets a reference to the given time.Time and assigns it to the DateTransaction field.
func (o *TransactionResponseV2) SetDateTransaction(v time.Time) {
	o.DateTransaction = &v
}

func (o TransactionResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PublicId) {
		toSerialize["publicId"] = o.PublicId
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.CodeEnvoi) {
		toSerialize["codeEnvoi"] = o.CodeEnvoi
	}
	if !IsNil(o.Montant) {
		toSerialize["montant"] = o.Montant
	}
	if !IsNil(o.FraisEnvoi) {
		toSerialize["fraisEnvoi"] = o.FraisEnvoi
	}
	if !IsNil(o.Reduction) {
		toSerialize["reduction"] = o.Reduction
	}
	if !IsNil(o.FraisInclus) {
		toSerialize["fraisInclus"] = o.FraisInclus
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.StatusTransaction) {
		toSerialize["statusTransaction"] = o.StatusTransaction
	}
	if !IsNil(o.TypeTransaction) {
		toSerialize["typeTransaction"] = o.TypeTransaction
	}
	if !IsNil(o.TypeOperation) {
		toSerialize["typeOperation"] = o.TypeOperation
	}
	if !IsNil(o.NomExpediteur) {
		toSerialize["nomExpediteur"] = o.NomExpediteur
	}
	if !IsNil(o.PrenomExpediteur) {
		toSerialize["prenomExpediteur"] = o.PrenomExpediteur
	}
	if !IsNil(o.TelephoneExpediteur) {
		toSerialize["telephoneExpediteur"] = o.TelephoneExpediteur
	}
	if !IsNil(o.NomDestinataire) {
		toSerialize["nomDestinataire"] = o.NomDestinataire
	}
	if !IsNil(o.PrenomDestinataire) {
		toSerialize["prenomDestinataire"] = o.PrenomDestinataire
	}
	if !IsNil(o.TelephoneDestinataire) {
		toSerialize["telephoneDestinataire"] = o.TelephoneDestinataire
	}
	if !IsNil(o.VilleDestinataire) {
		toSerialize["villeDestinataire"] = o.VilleDestinataire
	}
	if !IsNil(o.PaysDestinataire) {
		toSerialize["paysDestinataire"] = o.PaysDestinataire
	}
	if !IsNil(o.DateTransaction) {
		toSerialize["dateTransaction"] = o.DateTransaction
	}
	return toSerialize, nil
}

type NullableTransactionResponseV2 struct {
	value *TransactionResponseV2
	isSet bool
}

func (v NullableTransactionResponseV2) Get() *TransactionResponseV2 {
	return v.value
}

func (v *NullableTransactionResponseV2) Set(val *TransactionResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionResponseV2(val *TransactionResponseV2) *NullableTransactionResponseV2 {
	return &NullableTransactionResponseV2{value: val, isSet: true}
}

func (v NullableTransactionResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


