/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateEnvoiDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateEnvoiDto{}

// UpdateEnvoiDto struct for UpdateEnvoiDto
type UpdateEnvoiDto struct {
	CodeEnvoi string `json:"codeEnvoi"`
	RequestId string `json:"requestId"`
	IndicatifExpediteur string `json:"indicatifExpediteur" validate:"regexp=^\\\\+?\\\\d{2,6}$"`
	NumeroExpediteur string `json:"numeroExpediteur" validate:"regexp=^\\\\d{4,15}$"`
	NomDestinataire string `json:"nomDestinataire"`
	PrenomDestinataire string `json:"prenomDestinataire"`
	IndicatifDestinataire string `json:"indicatifDestinataire" validate:"regexp=^\\\\+?\\\\d{2,6}$"`
	NumeroDestinataire string `json:"numeroDestinataire" validate:"regexp=^\\\\d{4,15}$"`
	VilleDestination string `json:"villeDestination"`
}

type _UpdateEnvoiDto UpdateEnvoiDto

// NewUpdateEnvoiDto instantiates a new UpdateEnvoiDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateEnvoiDto(codeEnvoi string, requestId string, indicatifExpediteur string, numeroExpediteur string, nomDestinataire string, prenomDestinataire string, indicatifDestinataire string, numeroDestinataire string, villeDestination string) *UpdateEnvoiDto {
	this := UpdateEnvoiDto{}
	this.CodeEnvoi = codeEnvoi
	this.RequestId = requestId
	this.IndicatifExpediteur = indicatifExpediteur
	this.NumeroExpediteur = numeroExpediteur
	this.NomDestinataire = nomDestinataire
	this.PrenomDestinataire = prenomDestinataire
	this.IndicatifDestinataire = indicatifDestinataire
	this.NumeroDestinataire = numeroDestinataire
	this.VilleDestination = villeDestination
	return &this
}

// NewUpdateEnvoiDtoWithDefaults instantiates a new UpdateEnvoiDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateEnvoiDtoWithDefaults() *UpdateEnvoiDto {
	this := UpdateEnvoiDto{}
	return &this
}

// GetCodeEnvoi returns the CodeEnvoi field value
func (o *UpdateEnvoiDto) GetCodeEnvoi() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CodeEnvoi
}

// GetCodeEnvoiOk returns a tuple with the CodeEnvoi field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetCodeEnvoiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CodeEnvoi, true
}

// SetCodeEnvoi sets field value
func (o *UpdateEnvoiDto) SetCodeEnvoi(v string) {
	o.CodeEnvoi = v
}

// GetRequestId returns the RequestId field value
func (o *UpdateEnvoiDto) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *UpdateEnvoiDto) SetRequestId(v string) {
	o.RequestId = v
}

// GetIndicatifExpediteur returns the IndicatifExpediteur field value
func (o *UpdateEnvoiDto) GetIndicatifExpediteur() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndicatifExpediteur
}

// GetIndicatifExpediteurOk returns a tuple with the IndicatifExpediteur field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetIndicatifExpediteurOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndicatifExpediteur, true
}

// SetIndicatifExpediteur sets field value
func (o *UpdateEnvoiDto) SetIndicatifExpediteur(v string) {
	o.IndicatifExpediteur = v
}

// GetNumeroExpediteur returns the NumeroExpediteur field value
func (o *UpdateEnvoiDto) GetNumeroExpediteur() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NumeroExpediteur
}

// GetNumeroExpediteurOk returns a tuple with the NumeroExpediteur field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetNumeroExpediteurOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumeroExpediteur, true
}

// SetNumeroExpediteur sets field value
func (o *UpdateEnvoiDto) SetNumeroExpediteur(v string) {
	o.NumeroExpediteur = v
}

// GetNomDestinataire returns the NomDestinataire field value
func (o *UpdateEnvoiDto) GetNomDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NomDestinataire
}

// GetNomDestinataireOk returns a tuple with the NomDestinataire field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetNomDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NomDestinataire, true
}

// SetNomDestinataire sets field value
func (o *UpdateEnvoiDto) SetNomDestinataire(v string) {
	o.NomDestinataire = v
}

// GetPrenomDestinataire returns the PrenomDestinataire field value
func (o *UpdateEnvoiDto) GetPrenomDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrenomDestinataire
}

// GetPrenomDestinataireOk returns a tuple with the PrenomDestinataire field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetPrenomDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrenomDestinataire, true
}

// SetPrenomDestinataire sets field value
func (o *UpdateEnvoiDto) SetPrenomDestinataire(v string) {
	o.PrenomDestinataire = v
}

// GetIndicatifDestinataire returns the IndicatifDestinataire field value
func (o *UpdateEnvoiDto) GetIndicatifDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndicatifDestinataire
}

// GetIndicatifDestinataireOk returns a tuple with the IndicatifDestinataire field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetIndicatifDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndicatifDestinataire, true
}

// SetIndicatifDestinataire sets field value
func (o *UpdateEnvoiDto) SetIndicatifDestinataire(v string) {
	o.IndicatifDestinataire = v
}

// GetNumeroDestinataire returns the NumeroDestinataire field value
func (o *UpdateEnvoiDto) GetNumeroDestinataire() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NumeroDestinataire
}

// GetNumeroDestinataireOk returns a tuple with the NumeroDestinataire field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetNumeroDestinataireOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NumeroDestinataire, true
}

// SetNumeroDestinataire sets field value
func (o *UpdateEnvoiDto) SetNumeroDestinataire(v string) {
	o.NumeroDestinataire = v
}

// GetVilleDestination returns the VilleDestination field value
func (o *UpdateEnvoiDto) GetVilleDestination() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VilleDestination
}

// GetVilleDestinationOk returns a tuple with the VilleDestination field value
// and a boolean to check if the value has been set.
func (o *UpdateEnvoiDto) GetVilleDestinationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VilleDestination, true
}

// SetVilleDestination sets field value
func (o *UpdateEnvoiDto) SetVilleDestination(v string) {
	o.VilleDestination = v
}

func (o UpdateEnvoiDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateEnvoiDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["codeEnvoi"] = o.CodeEnvoi
	toSerialize["requestId"] = o.RequestId
	toSerialize["indicatifExpediteur"] = o.IndicatifExpediteur
	toSerialize["numeroExpediteur"] = o.NumeroExpediteur
	toSerialize["nomDestinataire"] = o.NomDestinataire
	toSerialize["prenomDestinataire"] = o.PrenomDestinataire
	toSerialize["indicatifDestinataire"] = o.IndicatifDestinataire
	toSerialize["numeroDestinataire"] = o.NumeroDestinataire
	toSerialize["villeDestination"] = o.VilleDestination
	return toSerialize, nil
}

func (o *UpdateEnvoiDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"codeEnvoi",
		"requestId",
		"indicatifExpediteur",
		"numeroExpediteur",
		"nomDestinataire",
		"prenomDestinataire",
		"indicatifDestinataire",
		"numeroDestinataire",
		"villeDestination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateEnvoiDto := _UpdateEnvoiDto{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateEnvoiDto)

	if err != nil {
		return err
	}

	*o = UpdateEnvoiDto(varUpdateEnvoiDto)

	return err
}

type NullableUpdateEnvoiDto struct {
	value *UpdateEnvoiDto
	isSet bool
}

func (v NullableUpdateEnvoiDto) Get() *UpdateEnvoiDto {
	return v.value
}

func (v *NullableUpdateEnvoiDto) Set(val *UpdateEnvoiDto) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateEnvoiDto) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateEnvoiDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateEnvoiDto(val *UpdateEnvoiDto) *NullableUpdateEnvoiDto {
	return &NullableUpdateEnvoiDto{value: val, isSet: true}
}

func (v NullableUpdateEnvoiDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateEnvoiDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


