/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerificationCompteDtoV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationCompteDtoV2{}

// VerificationCompteDtoV2 struct for VerificationCompteDtoV2
type VerificationCompteDtoV2 struct {
	IndicatifPhoneClient string `json:"indicatifPhoneClient" validate:"regexp=^\\\\d{2,6}$"`
	PhoneClient string `json:"phoneClient" validate:"regexp=^\\\\d{4,15}$"`
	AdresseIp *string `json:"adresseIp,omitempty" validate:"regexp=^((\\\\d{1,3}\\\\.){3}\\\\d{1,3}|[0-9a-fA-F:]{3,39})?$"`
}

type _VerificationCompteDtoV2 VerificationCompteDtoV2

// NewVerificationCompteDtoV2 instantiates a new VerificationCompteDtoV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationCompteDtoV2(indicatifPhoneClient string, phoneClient string) *VerificationCompteDtoV2 {
	this := VerificationCompteDtoV2{}
	this.IndicatifPhoneClient = indicatifPhoneClient
	this.PhoneClient = phoneClient
	return &this
}

// NewVerificationCompteDtoV2WithDefaults instantiates a new VerificationCompteDtoV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationCompteDtoV2WithDefaults() *VerificationCompteDtoV2 {
	this := VerificationCompteDtoV2{}
	return &this
}

// GetIndicatifPhoneClient returns the IndicatifPhoneClient field value
func (o *VerificationCompteDtoV2) GetIndicatifPhoneClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IndicatifPhoneClient
}

// GetIndicatifPhoneClientOk returns a tuple with the IndicatifPhoneClient field value
// and a boolean to check if the value has been set.
func (o *VerificationCompteDtoV2) GetIndicatifPhoneClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IndicatifPhoneClient, true
}

// SetIndicatifPhoneClient sets field value
func (o *VerificationCompteDtoV2) SetIndicatifPhoneClient(v string) {
	o.IndicatifPhoneClient = v
}

// GetPhoneClient returns the PhoneClient field value
func (o *VerificationCompteDtoV2) GetPhoneClient() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PhoneClient
}

// GetPhoneClientOk returns a tuple with the PhoneClient field value
// and a boolean to check if the value has been set.
func (o *VerificationCompteDtoV2) GetPhoneClientOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PhoneClient, true
}

// SetPhoneClient sets field value
func (o *VerificationCompteDtoV2) SetPhoneClient(v string) {
	o.PhoneClient = v
}

// GetAdresseIp returns the AdresseIp field value if set, zero value otherwise.
func (o *VerificationCompteDtoV2) GetAdresseIp() string {
	if o == nil || IsNil(o.AdresseIp) {
		var ret string
		return ret
	}
	return *o.AdresseIp
}

// GetAdresseIpOk returns a tuple with the AdresseIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerificationCompteDtoV2) GetAdresseIpOk() (*string, bool) {
	if o == nil || IsNil(o.AdresseIp) {
		return nil, false
	}
	return o.AdresseIp, true
}

// HasAdresseIp returns a boolean if a field has been set.
func (o *VerificationCompteDtoV2) HasAdresseIp() bool {
	if o != nil && !IsNil(o.AdresseIp) {
		return true
	}

	return false
}

// SetAdresseIp gets a reference to the given string and assigns it to the AdresseIp field.
func (o *VerificationCompteDtoV2) SetAdresseIp(v string) {
	o.AdresseIp = &v
}

func (o VerificationCompteDtoV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationCompteDtoV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["indicatifPhoneClient"] = o.IndicatifPhoneClient
	toSerialize["phoneClient"] = o.PhoneClient
	if !IsNil(o.AdresseIp) {
		toSerialize["adresseIp"] = o.AdresseIp
	}
	return toSerialize, nil
}

func (o *VerificationCompteDtoV2) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"indicatifPhoneClient",
		"phoneClient",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerificationCompteDtoV2 := _VerificationCompteDtoV2{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerificationCompteDtoV2)

	if err != nil {
		return err
	}

	*o = VerificationCompteDtoV2(varVerificationCompteDtoV2)

	return err
}

type NullableVerificationCompteDtoV2 struct {
	value *VerificationCompteDtoV2
	isSet bool
}

func (v NullableVerificationCompteDtoV2) Get() *VerificationCompteDtoV2 {
	return v.value
}

func (v *NullableVerificationCompteDtoV2) Set(val *VerificationCompteDtoV2) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationCompteDtoV2) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationCompteDtoV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationCompteDtoV2(val *VerificationCompteDtoV2) *NullableVerificationCompteDtoV2 {
	return &NullableVerificationCompteDtoV2{value: val, isSet: true}
}

func (v NullableVerificationCompteDtoV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationCompteDtoV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


