/*
Nita transfert d'argent | Niger Poste

APIs partenaires NITA.  Perimetre : endpoints v2 (/api/v2/_**).  Deux couches d'erreurs, a ne pas confondre :  - TRANSPORT (vrais statuts HTTP) : 400 (corps invalide, en-tetes de   signature absents/malformes), 401 (cle, jeton Bearer ou signature   invalides, horodatage perime), 403 (produit non souscrit, jeton   invalide/expire). - METIER : renvoyee en HTTP 200, le vrai code se trouve dans l'enveloppe   {status, code, message, data} - par exemple 402, 404, 405, 409   (requestId deja utilise), 500. Testez le champ `code` du corps, pas le   seul statut HTTP.  Signature (POST/PUT) : hex(HMAC-SHA256(secret_partenaire, timestamp + \" \" + nonce + \" \" + corps)), portee par X-NT-TIMESTAMP, X-NT-NONCE et X-NT-SIGNATURE. Les SDK officiels la calculent et la posent au niveau transport. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nita

import (
	"encoding/json"
)

// checks if the CheckAchatStatusResponseV2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckAchatStatusResponseV2{}

// CheckAchatStatusResponseV2 struct for CheckAchatStatusResponseV2
type CheckAchatStatusResponseV2 struct {
	Code *string `json:"code,omitempty"`
	Description *string `json:"description,omitempty"`
	CodeAchat *string `json:"codeAchat,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewCheckAchatStatusResponseV2 instantiates a new CheckAchatStatusResponseV2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckAchatStatusResponseV2() *CheckAchatStatusResponseV2 {
	this := CheckAchatStatusResponseV2{}
	return &this
}

// NewCheckAchatStatusResponseV2WithDefaults instantiates a new CheckAchatStatusResponseV2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckAchatStatusResponseV2WithDefaults() *CheckAchatStatusResponseV2 {
	this := CheckAchatStatusResponseV2{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *CheckAchatStatusResponseV2) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusResponseV2) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *CheckAchatStatusResponseV2) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *CheckAchatStatusResponseV2) SetCode(v string) {
	o.Code = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CheckAchatStatusResponseV2) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusResponseV2) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CheckAchatStatusResponseV2) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CheckAchatStatusResponseV2) SetDescription(v string) {
	o.Description = &v
}

// GetCodeAchat returns the CodeAchat field value if set, zero value otherwise.
func (o *CheckAchatStatusResponseV2) GetCodeAchat() string {
	if o == nil || IsNil(o.CodeAchat) {
		var ret string
		return ret
	}
	return *o.CodeAchat
}

// GetCodeAchatOk returns a tuple with the CodeAchat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusResponseV2) GetCodeAchatOk() (*string, bool) {
	if o == nil || IsNil(o.CodeAchat) {
		return nil, false
	}
	return o.CodeAchat, true
}

// HasCodeAchat returns a boolean if a field has been set.
func (o *CheckAchatStatusResponseV2) HasCodeAchat() bool {
	if o != nil && !IsNil(o.CodeAchat) {
		return true
	}

	return false
}

// SetCodeAchat gets a reference to the given string and assigns it to the CodeAchat field.
func (o *CheckAchatStatusResponseV2) SetCodeAchat(v string) {
	o.CodeAchat = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CheckAchatStatusResponseV2) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckAchatStatusResponseV2) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CheckAchatStatusResponseV2) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CheckAchatStatusResponseV2) SetRequestId(v string) {
	o.RequestId = &v
}

func (o CheckAchatStatusResponseV2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckAchatStatusResponseV2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CodeAchat) {
		toSerialize["codeAchat"] = o.CodeAchat
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableCheckAchatStatusResponseV2 struct {
	value *CheckAchatStatusResponseV2
	isSet bool
}

func (v NullableCheckAchatStatusResponseV2) Get() *CheckAchatStatusResponseV2 {
	return v.value
}

func (v *NullableCheckAchatStatusResponseV2) Set(val *CheckAchatStatusResponseV2) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckAchatStatusResponseV2) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckAchatStatusResponseV2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckAchatStatusResponseV2(val *CheckAchatStatusResponseV2) *NullableCheckAchatStatusResponseV2 {
	return &NullableCheckAchatStatusResponseV2{value: val, isSet: true}
}

func (v NullableCheckAchatStatusResponseV2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckAchatStatusResponseV2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


